import type { Shop } from "./types";

export const alaskaShops: Shop[] = [
    {
        id: "1",
        slug: "fifth-avenue-cgars",
        name: "5th Avenue Cigars",
        city: "Anchorage",
        stateabb: "AK",
        state: "Alaska",
        zip: "99501",
        address: "531 E 5th Ave, Anchorage, AK 99501",
        phone: "(907) 274-7473",
        website: "http://www.avenuecigars.com",
        hours: {
            mon: "10 AM-8 PM",
            tue: "10 AM-8 PM",
            wed: "10 AM-8 PM",
            thu: "10 AM-8 PM",
            fri: "10 AM-8 PM",
            sat: "10 AM-8 PM",
            sun: "3PM-9 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 61.217821,
        longitude: -149.874144,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]