import type { Shop } from "./types";

export const arizonaShops: Shop[] = [
    {
        id: "1",
        slug: "castro-cigar-lounge",
        name: "Castro's Cigar Lounge",
        city: "Phoenix",
        stateabb: "AZ",
        state: "Arizona",
        zip: "85044",
        address: "4855 E Warner Rd, Phoenix, AZ, 85044",
        phone: "(480) 687-2850",
        website: "https://castroscigarbar.com/phoenix-cigar-bar/",
        hours: {
            mon: "10AM - Midnight",
            tue: "10AM - Midnight",
            wed: "10AM - Midnight",
            thu: "10 AM - 2 AM",
            fri: "10 AM - 2 AM",
            sat: "10 AM - 2 AM",
            sun: "10AM - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Our full craft bar in Phoenix (Ahwatukee) is designed for the discerning spirits enthusiast. From world-renowned whiskies + bourbons, to boutique and small batch releases - we've curated an amazing selection for you to enjoy.",
        latitude: 33.330843,
        longitude: -111.978521,
        image: "/images/castroaz/img1.jpg",
        gallery: [
            "/images/castroaz/img1.jpg",
            "/images/castroaz/img2.jpg",

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    ]