import type { Shop } from "./types";

export const arkansasShops: Shop[] = [
    {
        id: "1",
        slug: "cigar-republic",
        name: "Cigar Republic",
        city: "Little Rock",
        stateabb: "AR",
        state: "Arkansas",
        zip: "72227",
        address: "1315 Breckenridge Dr, Little Rock, AR 72227",
        phone: "(501) 615-8040",
        website: "https://www.cigarrepublic.com/",
        hours: {
            mon: "1PM - 11PM",
            tue: "1PM - 11PM",
            wed: "1PM - 11PM",
            thu: "1PM - Midnight",
            fri: "1PM - Midnight",
            sat: "11AM - Midnight",
            sun: "3PM - 10PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Arkansas' Largest Walk-In Humidor",
        latitude: 34.766697,
        longitude: -92.386303,
        image: "/images/shops/republicAR/img1.jpg",
        gallery: [
            "/images/shops/republicAR/img1.jpg",
            "/images/shops/republicAR/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]