import type { Shop } from "./types";

export const californiaShops: Shop[] = [
    {
        id: "30",
        slug: "churchill-cigar-lounge",
        name: "Churchill Cigar Lounge",
        city: "San Diego",
        stateabb: "CA",
        state: "California",
        zip: "92110",
        address: "2415 San Diego Ave, San Diego, CA 92110",
        phone: "(619) 546-7758",
        website: "https://churchillcigarlounge.com/",
        hours: {
            mon: "10AM - 10PM",
            tue: "10AM - 10PM",
            wed: "10AM - 10PM",
            thu: "10AM - 10PM",
            fri: "10AM - 12AM",
            sat: "10AM - 12AM",
            sun: "10AM - 10PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
                
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 32.751718,
        longitude: -117.193959,
        image: "/images/churchill-sd/patio.jpeg",
        gallery: [
            "/images/churchill-sd/patio.jpeg",
            "/images/churchill-sd/cigarlist.png",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]