import type { Shop } from "./types";

export const connecticutShops: Shop[] = [
    {
        id: "1",
        slug: "prime-tobacconist-club",
        name: "Prime Tobacconist Club",
        city: "Milford",
        stateabb: "CT",
        state: "Connecticut",
        zip: "06460",
        address: "884 Boston Post Road, Milford, Connecticut 06460",
        phone: "(203) 283-0699",
        website: "https://www.primetobacconist.com/",
        hours: {
            mon: "Noon - 9PM",
            tue: "Noon - 9PM",
            wed: "Noon - 11PM",
            thu: "Noon - 11PM",
            fri: "Noon - 11PM",
            sat: "Noon - 11PM", 
            sun: "Noon - 9PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "We welcome all cigar lovers to our lounge without the necessity of a membership. In alignment with our policies, we respectfully ask that guests refrain from bringing cigars from external sources into the lounge. BYOB is welcomed in our lounge for a fee. Browse our humidor and collection of curated gifts for cigar enthusiasts, or inquire about private event rentals. Stay updated with our latest offerings and events by joining our mailing list.",
        latitude: 41.232254,
        longitude: -73.051541,
        image: "",
        gallery: [
            "",
            
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]