import type { Shop } from "./types";

export const washingtondcShops: Shop[] = [
    {
        id: "1",
        slug: "wperiod-curtis-draper-tobacoonist",
        name: "W. Curtis Draper Tobacconist",
        city: "Washington, D.C.",
        stateabb: "DC",
        state: "Washington, D.C.",
        zip: "20005",
        address: "699 15th St NW, Washington, DC 20005",
        phone: "(202) 638-2555",
        website: "http://www.wcurtisdraper.com",
        hours: {
            mon: "10 AM-5 PM",
            tue: "10 AM-5 PM",
            wed: "10 AM-5 PM",
            thu: "10 AM-5 PM",
            fri: "10 AM-5 PM",
            sat: "Closed",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 38.8985,
        longitude: -77.033368,
        image: "/images/drapersDC/img1.jpg",
        gallery: [
            "/images/drapersDC/img1.jpg",
            "/images/drapersDC/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "2",
        slug: "casa-de-montecristo",
        name: "Casa de Montecristo Cigar Lounge",
        city: "Washington, D.C.",
        stateabb: "DC",
        state: "Washington, D.C.",
        zip: "20036",
        address: "1132 19th St NW, Washington, DC 20036",
        phone: "(202) 296-3872",
        website: "https://www.casademontecristo.com/washington-dc/?utm_source=partnerize&utm_medium=affiliate&utm_campaign=206204&utm_content=8-12854&clickId=5467141669",
        hours: {
            mon: "10AM - 10PM",
            tue: "10AM - 10PM",
            wed: "10AM - 10PM",
            thu: "10AM - 10PM",
            fri: "10AM - 1AM",
            sat: "10AM - 1AM",
            sun: "12PM - 10PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The White House may be the most famous residence in the city, but the Casa de Montecristo cigar shop spanning two floors, totaling 4,000 square feet, takes precedence when it comes to cigar bars in Washington DC. ",
        latitude: 38.8949,
        longitude: -77.0000,
        image: "/images/casaDC/1.jpg",
        gallery: [
            "/images/casaDC/1.jpg",
            "/images/casaDC/2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "3",
        slug: "shelly-back-room",
        name: "Shelly's Back Room",
        city: "Washington, D.C.",
        stateabb: "DC",
        state: "Washington, D.C.",
        zip: "20004",
        address: "1331 F St NW, Washington, DC 20004",
        phone: "(202) 737-3003",
        website: "http://shellysbackroom.com",
        hours: {
            mon: "1130AM - Midnight",
            tue: "1130AM - 2AM",
            wed: "1130AM - 2AM",
            thu: "1130AM - 2AM",
            fri: "1130AM - 2AM",
            sat: "1130AM - 2AM",
            sun: "Noon - Midnight"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: true,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Well known cigar lounge and fine restaurant",
        latitude: 38.897644,
        longitude: -77.03095,
        image: "/images/shellyDC/1.jpg",
        gallery: [
            "/images/shellyDC/1.jpg",
            "/images/shellyDC/2.jpg",
            "/images/shellyDC/3.jpg",
            "/images/shellyDC/4.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]