import type { Shop } from "./types";

export const washingtondcShops: Shop[] = [
    {
        id: "1",
        slug: "wperiod-curtis-draper-tobacoonist",
        name: "W. Curtis Draper Tobacconist",
        city: "Anchorage",
        stateabb: "DC",
        state: "Washington DC",
        zip: "2005",
        address: "699 15th St NW, Washington, DC 20005",
        phone: "(202) 638-2555",
        website: "http://www.wcurtisdraper.com",
        hours: {
            mon: "10 AM-5 PM",
            tue: "10 AM-5 PM",
            wed: "10 AM-5 PM",
            thu: "10 AM-5 PM",
            fri: "10 AM-5 PM",
            sat: "Closed",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 38.8985,
        longitude: -77.033368,
        image: "/images/drapersDC/img1.jpg",
        gallery: [
            "/images/drapersDC/img1.jpg",
            "/images/drapersDC/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]