import type { Shop } from "./types";

export const delawareShops: Shop[] = [
    {
        id: "1",
        slug: "the-sikar-cigar-lounge",
        name: "The Sikar Cigar Lounge",
        city: "Wilmington",
        stateabb: "DE",
        state: "Delaware",
        zip: "19806",
        address: "1624 Delaware Ave, Wilmington, DE 19806",
        phone: "(302) 655-2250",
        website: "https://www.facebook.com › SikarLounge",
        hours: {
            mon: "5PM - 12AM",
            tue: "5PM - 12AM",
            wed: "5PM - 12AM",
            thu: "5PM - 12AM",
            fri: "2PM - 1 AM",
            sat: "2PM - 1 AM",
            sun: "5PM - 12AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Delaware's premiere cigar lounge located in the heart of Trolley Square!.",
        latitude: 39.757679,
        longitude: -75.562577,
        image: "/images/shops/sikarde/img1.jpg",
        gallery: [
            "/images/shops/sikarde/img1.jpg",
            "/images/shops/sikarde/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]