import type { Shop } from "./types";

export const floridaShops: Shop[] = [
    {
        id: "3",
        slug: "bonita-smoke-shop-and-cigar-lounge",
        name: "Bonita Smoke Shop & Cigar Lounge",
        city: "Estero",
        stateabb: "FL",
        state: "Florida",
        zip: "33928",
        address: "23050 Via Villagio Pkwy, Estero, FL 33928",
        phone: "(239) 495-9296",
        website: "http://www.bonitasmokeshop.com",
        hours: {
            mon: "9AM - 9PM",
            tue: "9AM - 9PM",
            wed: "9AM - 9PM",
            thu: "9AM - 9PM",
            fri: "9AM - 9PM",
            sat: "9AM - 9PM", 
            sun: "10AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Bonita Beach, FL – Bonita Smoke Shop, a beloved local institution for over 30 years, is thrilled to announce its relocation and expansion to Coconut Point Shopping Center will be operating under Bonita Smoke Shop & Cigar Lounge.  The new location will feature a significantly expanded retail space boasting over 6,600 square feet dedicated to a world-class selection of cigars.",
        latitude: 26.40693,
        longitude: -81.809575,
        image: "/images/bonita/front.jpg",
        gallery: [
            "/images/bonita/front.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "5",
        slug: "burn-by-rocky-patel-naples",
        name: "BURN by Rocky Patel- Naples",
        city: "Naples",
        stateabb: "FL",
        state: "Florida",
        zip: "34108",
        address: "9110 Strada Pl, Naples, FL 34108",
        phone: "(239) 653-9013",
        website: "https://www.burnbyrockypatel.com › naples",
        hours: {
            mon: "2PM - 2AM",
            tue: "2PM - 2AM",
            wed: "2PM - 2AM",
            thu: "2PM - 2AM",
            fri: "2PM - 2AM",
            sat: "2PM - 2AM",
            sun: "2PM - 2AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "This place looks amazing!",
        latitude: 26.25305,
        longitude: -81.798937,
        image: "/images/burnNaples/1.jpg",
        gallery: [
            "/images/burnNaples/1.jpg",
            "/images/burnNaples/2.jpg",
            "/images/burnNaples/3.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "6",
        slug: "corona-cigar-company-and-diamond-crown-lounge",
        name: "Corona Cigar Company & Diamond Crown Lounge",
        city: "Orlando",
        stateabb: "FL",
        state: "Florida",
        zip: "32801",
        address: "127 S Orange Ave, Orlando, FL 32801",
        phone: "(407) 404-5344",
        website: "https://www.coronacigar.com",
        hours: {
            mon: "9AM - Midnight",
            tue: "9AM - Midnight",
            wed: "9AM - 1AM",
            thu: "9AM - 1AM",
            fri: "9AM - 1AM",
            sat: "9AM - 1AM",
            sun: "10AM - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "This place looks amazing!",
        latitude: 28.541091,
        longitude: -81.378729,
        image: "/images/coronaFL/1.jpg",
        gallery: [
            "/images/coronaFL/1.jpg",
            "/images/coronaFL/2.jpg",
            "/images/coronaFL/3.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
]