import type { Shop } from "./types";

export const floridaShops: Shop[] = [
    {
        id: "3",
        slug: "bonita-smoke-shop-and-cigar-lounge",
        name: "Bonita Smoke Shop & Cigar Lounge",
        city: "Estero",
        stateabb: "FL",
        state: "Florida",
        zip: "33928",
        address: "23050 Via Villagio Pkwy, Estero, FL 33928",
        phone: "(239) 495-9296",
        website: "http://www.bonitasmokeshop.com",
        hours: {
            mon: "9AM - 9PM",
            tue: "9AM - 9PM",
            wed: "9AM - 9PM",
            thu: "9AM - 9PM",
            fri: "9AM - 9PM",
            sat: "9AM - 9PM", 
            sun: "10AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Bonita Beach, FL – Bonita Smoke Shop, a beloved local institution for over 30 years, is thrilled to announce its relocation and expansion to Coconut Point Shopping Center will be operating under Bonita Smoke Shop & Cigar Lounge.  The new location will feature a significantly expanded retail space boasting over 6,600 square feet dedicated to a world-class selection of cigars.",
        latitude: 26.40693,
        longitude: -81.809575,
        image: "/images/shops/bonita/front.jpg",
        gallery: [
            "/images/shops/bonita/front.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "5",
        slug: "burn-by-rocky-patel-naples",
        name: "BURN by Rocky Patel- Naples",
        city: "Naples",
        stateabb: "FL",
        state: "Florida",
        zip: "34108",
        address: "9110 Strada Pl, Naples, FL 34108",
        phone: "(239) 653-9013",
        website: "https://www.burnbyrockypatel.com › naples",
        hours: {
            mon: "2PM - 2AM",
            tue: "2PM - 2AM",
            wed: "2PM - 2AM",
            thu: "2PM - 2AM",
            fri: "2PM - 2AM",
            sat: "2PM - 2AM",
            sun: "2PM - 2AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "This place looks amazing!",
        latitude: 26.25305,
        longitude: -81.798937,
        image: "/images/shops/burnNaples/1.jpg",
        gallery: [
            "/images/shops/burnNaples/1.jpg",
            "/images/shops/burnNaples/2.jpg",
            "/images/shops/burnNaples/3.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "6",
        slug: "corona-cigar-company-and-diamond-crown-lounge",
        name: "Corona Cigar Company & Diamond Crown Lounge",
        city: "Orlando",
        stateabb: "FL",
        state: "Florida",
        zip: "32801",
        address: "127 S Orange Ave, Orlando, FL 32801",
        phone: "(407) 404-5344",
        website: "https://www.coronacigar.com",
        hours: {
            mon: "9AM - Midnight",
            tue: "9AM - Midnight",
            wed: "9AM - 1AM",
            thu: "9AM - 1AM",
            fri: "9AM - 1AM",
            sat: "9AM - 1AM",
            sun: "10AM - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "This place looks amazing!",
        latitude: 28.541091,
        longitude: -81.378729,
        image: "/images/shops/coronaFL/1.jpg",
        gallery: [
            "/images/shops/coronaFL/1.jpg",
            "/images/shops/coronaFL/2.jpg",
            "/images/shops/coronaFL/3.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "7",
        slug: "davidoff-of-geneva-hollywood-florida",
        name: "Davidoff of Geneva - Hollywood, FL",
        city: "Hollywood",
        stateabb: "FL",
        state: "Florida",
        zip: "33314",
        address: "5804 Seminole Way Suite 113, Hollywood, FL 33314",
        phone: "954-488-6980",
        website: "https://us.davidoffgeneva.com/store-locator?page=2",
        hours: {
            mon: "9AM - Midnight",
            tue: "9AM - Midnight",
            wed: "9AM - 1AM",
            thu: "9AM - 1AM",
            fri: "9AM - 1AM",
            sat: "9AM - 1AM",
            sun: "10AM - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: false,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: false,
        hasDavidoff: true,
        hasAvo: false,
        hasLiga: false,
        hasAcid: false,
        hasTatuaje: false,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "This place looks amazing!",
        latitude: 26.050488,
        longitude: -80.208096,
        image: "/images/shops/davidoffHollywood/1.jpg",
        gallery: [
            "/images/shops/davidoffHollywood/1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.2,
        reviewCount: 102,
    },
    {
        id: "8",
        slug: "cigars-cigars-sarasota-florida",
        name: "Cigar, Cigars - University at Parkway",
        city: "Sarasota",
        stateabb: "FL",
        state: "Florida",
        zip: "34243",
        address: "6396 Lockwood Ridge Rd, Sarasota, FL 34243",
        phone: "(941) 413-7380",
        website: "http://cigarcigars.com",
        hours: {
            mon: "10AM - 8PM",
            tue: "10AM - 8PM",
            wed: "10AM - 8PM",
            thu: "10AM - 8PM",
            fri: "10AM - 8PM",
            sat: "10AM - 8PM",
            sun: "10AM - 5PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: false,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: false,
        hasDavidoff: true,
        hasAvo: false,
        hasLiga: false,
        hasAcid: false,
        hasTatuaje: false,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "With three locations in the Sarasota, Florida area, Cigar Cigars offers a premium cigar experience built on decades of expertise. Established in 1995, we grew to become one of the largest cigar retailers in the Philadelphia region before bringing our passion for cigars to Florida in 2020. Today, we are proud to call Sarasota home.",
        latitude: 27.42693,
        longitude: -82.505542,
        image: "/images/shops/cigarcigarFL/1.jpg",
        gallery: [
            "/images/shops/cigarcigarFL/1.jpg",
            "/images/shops/cigarcigarFL/2.jpg",
            "/images/shops/cigarcigarFL/3.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.2,
        reviewCount: 102,
    },
    {
        id: "8",
        slug: "cigars-cigars-sarasota-clark",
        name: "Cigar, Cigars - Clark Rd.",
        city: "Sarasota",
        stateabb: "FL",
        state: "Florida",
        zip: "34243",
        address: "2881 Clark Rd, Unit 11,Sarasota, FL 34231",
        phone: "(941) 554-4283",
        website: "http://cigarcigars.com",
        hours: {
            mon: "10AM - 8PM",
            tue: "10AM - 8PM",
            wed: "10AM - 8PM",
            thu: "10AM - 8PM",
            fri: "10AM - 8PM",
            sat: "10AM - 8PM",
            sun: "10AM - 5PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: false,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: false,
        hasDavidoff: true,
        hasAvo: false,
        hasLiga: false,
        hasAcid: false,
        hasTatuaje: false,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "With three locations in the Sarasota, Florida area, Cigar Cigars offers a premium cigar experience built on decades of expertise. Established in 1995, we grew to become one of the largest cigar retailers in the Philadelphia region before bringing our passion for cigars to Florida in 2020. Today, we are proud to call Sarasota home.",
        latitude: 27.270669,
        longitude: -82.513012,
        image: "/images/shops/cigarcigarFL/ClarkRd.jpg",
        gallery: [
            "/images/shops/cigarcigarFL/ClarkRd.jpg",
            "/images/shops/cigarcigarFL/ClarkRd2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.2,
        reviewCount: 102,
    },
    {
        id: "9",
        slug: "corona-cigar-company-sarasota",
        name: "Corona Cigar Company and El Septimo Lounge",
        city: "Sarasota",
        stateabb: "FL",
        state: "Florida",
        zip: "34243",
        address: "22 N Lemon Ave, Sarasota, FL 34236",
        phone: "(941) 554-4283",
        website: "https://www.coronacigar.com",
        hours: {
            mon: "9AM - Midnight",
            tue: "9AM - Midnight",
            wed: "9AM - Midnight",
            thu: "9AM - 1AM",
            fri: "9AM - 1AM",
            sat: "9AM - 1AM",
            sun: "10AM - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: false,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: false,
        hasDavidoff: true,
        hasAvo: false,
        hasLiga: false,
        hasAcid: false,
        hasTatuaje: false,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Enormous place!",
        latitude: 27.337056,
        longitude: -82.540444,
        image: "/images/shops/coronaSarasota/1.jpg",
        gallery: [
            "/images/shops/coronaSarasota/1.jpg",
            "/images/shops/coronaSarasota/2.jpg",
            "/images/shops/coronaSarasota/3.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.2,
        reviewCount: 102,
    },
]