import type { Shop } from "./types";

export const georgiaShops: Shop[] = [
    {
        id: "1",
        slug: "prime-cigar-bar",
        name: "Prime Cigar",
        city: "Atlanta",
        stateabb: "GA",
        state: "Georgia",
        zip: "30309",
        address: "1035 Peachtree St NE, Atlanta, GA 30309",
        phone: "(404) 941-7130",
        website: "https://primecigaratl.com/",
        hours: {
            mon: "3PM - 1AM",
            tue: "3PM - 1AM",
            wed: "3PM - 1AM",
            thu: "3PM - 1AM",
            fri: "3PM - 1AM",
            sat: "3PM - 1AM",
            sun: "3PM - 1AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Welcome to Atlanta’s Most Premier Cigar Lounge. Let’s dine, drink, smoke.  Enjoy from a selection of our handcrafted cocktails or one of your favorite premium drinks. Our bartender will be sure to have you coming back all night long.",
        latitude: 33.782868,
        longitude: -84.383753,
        image: "/images/atlantaprime/InteriorShot-scaled.jpg",
        gallery: [
            "/images/atlantaprime/InteriorShot-scaled.jpg",
        ],
        isSponsored: false,
        rating: 3.1,
        reviewCount: 54,
    },
    ]