import type { Shop } from "./types";

export const idahoShops: Shop[] = [
    {
        id: "1",
        slug: "big-smoke",
        name: "Big Smoke",
        city: "Boise",
        stateabb: "ID",
        state: "Idaho",
        zip: "83704",
        address: "6595 W Ustick Rd, Boise, ID 83704",
        phone: "(208) 376-9333",
        website: "http://www.bigsmokestores.com",
        hours: {
            mon: "7AM - 10PM",
            tue: "7AM - 10PM",
            wed: "7AM - 10PM",
            thu: "7AM - 10PM",
            fri: "7AM - 10PM",
            sat: "7AM - 10PM",
            sun: "8AM - 9PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 43.633686,
        longitude: -116.263362,
        image: "/images/shops/bigsmokeidaho/img1.jpg",
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]