import type { Shop } from "./types";

export const illinoisShops: Shop[] = [
    {
        id: "1",
        slug: "Windy-city-cigar-lounge",
        name: "Windy City Cigar Lounge",
        city: "Chicago",
        stateabb: "IL",
        state: "Illinois",
        zip: "60653",
        address: "4310 S Prairie Ave, Chicago, IL 60653",
        phone: "(773) 855-2143",
        website: "",
        hours: {
            mon: "Closed",
            tue: "Closed",
            wed: "5PM - Midnight",
            thu: "5PM - Midnight",
            fri: "5PM - 1 AM",
            sat: "5PM - 1 AM",
            sun: "11AM - 11 PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "A cigar lounge for the sophisticated cigar aficionado",
        latitude: 41.816167,
        longitude: -87.620028,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
    },
    ]