import type { Shop } from "./types";

export const iowaShops: Shop[] = [
    {
        id: "1",
        slug: "iowa-cigar-company",
        name: "Iowa Cigar Company",
        city: "Des Moines",
        stateabb: "IA",
        state: "Iowa",
        zip: "50266",
        address: "1401 22nd St, West Des Moines, IA 50266",
        phone: "(515) 327-1255",
        website: "http://iowacigar.com",
        hours: {
            mon: "9AM - 7PM",
            tue: "9AM - 7PM",
            wed: "9AM - 7PM",
            thu: "9AM - 7PM",
            fri: "9AM - 7PM",
            sat: "9AM - 7PM",
            sun: "9AM - 7PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Founded in 1996, Iowa Cigar Company, formerly known as Pars & Cigars, is a local cigar shop in West Des Moines, Iowa. We have the largest cigar selection in Iowa. We also have a great smoking lounge and clientele which often meet for a premium cigar or two. Come join us for some excellent cigars.",
        latitude: 41.594296,
        longitude: -93.735401,
        image: "/images/shops/iowacigarIA/img1.jpg",
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]