import type { Shop } from "./types";

export const kentuckyShops: Shop[] = [
    {
        id: "1",
        slug: "wild-bill-cigar-bar-and-lounge",
        name: "Wild Bill's Cigar Bar & Lounge",
        city: "Georgetown",
        stateabb: "KY",
        state: "Kentucky",
        zip: "40324",
        address: "401 Outlet Center, Drive Suite 340, Georgetown, KY 40324",
        phone: "(859) 575-7015",
        website: "https://leafandbarrellounge.com/",
        hours: {
            mon: "2PM - 9PM",
            tue: "2PM - 9PM",
            wed: "2PM - 9PM",
            thu: "2PM - 9PM",
            fri: "2PM - 11PM",
            sat: "2PM - 11PM",
            sun: "1PM - 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Whether you’re new to the cigar scene or you’ve been enjoying premium hand-rolled cigars for many years, Leaf & Barrel Cigar and Bourbon Lounge is excited for you to visit us in Georgetown or in our NEW location at 103 Big Hill Ave. in Richmond!",
        latitude: 38.217645,
        longitude: -84.537132,
        image: "/images/shops/leafky/img1.jpg",
        gallery: [
            "/images/shops/leafky/img1.jpg",
            "/images/shops/leafky/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]