import type { Shop } from "./types";

export const maineShops: Shop[] = [
    {
        id: "1",
        slug: "cafe-calabash-cigar-bar",
        name: "Cafe Calabash Cigar Bar",
        city: "South Portland",
        stateabb: "ME",
        state: "Maine",
        zip: "04106",
        address: "425 Western Ave, South Portland, ME 04106",
        phone: "(207) 774-8673",
        website: "https://www.calabash-cafe.com",
        hours: {
            mon: "9 AM- 7PM",
            tue: "9 AM- 7PM",
            wed: "9 AM- 7PM",
            thu: "9 AM- 7PM",
            fri: "9 AM- 7PM",
            sat: "9 AM- 7PM",
            sun: "11AM- 5PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 43.642451,
        longitude: -70.327656,
        image: "/images/shops/cafeME/1.jpg",
        gallery: [
            "/images/shops/cafeME/1.jpg",
            "/images/shops/cafeME/2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]