import type { Shop } from "./types";

export const marylandShops: Shop[] = [
    {
        id: "1",
        slug: "davidus-cigars-annapolis",
        name: "Davidus Cigars- Annapolis",
        city: "Annapolis",
        stateabb: "MD",
        state: "Maryland",
        zip: "21401",
        address: "2134 Generals Hwy, Annapolis, MD 21401",
        phone: "(410) 573-1212",
        website: "http://www.davidus.com",
        hours: { mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: false,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: false, 
        hasPlasencia: true, 
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: true,
        hasIceMaker: true,
        hasBigTV: true,
        sellsAccessory: false,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 38.9784,
        longitude: -76.5434,
        image: "",
        gallery: [
            "/images/DavidusAnnapolis/JohnS.jpg", 
            
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 2.5,
        reviewCount: 131,
    },
    {
        id: "2",
        slug: "davidus-cigars-baltimore-federal-hill",
        name: "Davidus Cigars- Baltimore (Federal Hill)",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21230",
        address: "1011 Light St, Baltimore, MD 21230",
        phone: "(443) 449-5871",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: false, hasPlasencia: true, hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiveMusic: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.27794,
        longitude: -76.612265,
        image: "/images/fedhill/baltimore_light_st._8.jpg",
        gallery: [
            "/images/fedhill/baltimore_light_st._8.jpg",
            "/images/fedhill/wedsite-managerBAL-LS.jpeg",
            "/images/fedhill/baltimore_light_st._6.jpg",
            "/images/fedhill/baltimore_light_st._7.jpg"

        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "3",
        slug: "davidus-cigars-ellicott-city",
        name: "Davidus Cigars- Ellicott City",
        city: "Ellicott City",
        stateabb: "MD",
        state: "Maryland",
        zip: "21042",
        address: "9180 Baltimore National Pike, Ellicott City, MD 21042",
        phone: "(410) 480-4810",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: false,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: false, 
        hasPlasencia: true, 
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiveMusic: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.278012,
        longitude: -76.829263,
        image: "/images/DavidusEllicott/Ellicottfront.jpg",
        gallery: [
            "/images/DavidusEllicott/Ellicott_Citymgr.jpg",
            "/images/DavidusEllicott/cl-ellicottcity-8.jpg",
            "/images/DavidusEllicott/Ellicottfront.jpg",
            "/images/DavidusEllicott/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 1.9,
        reviewCount: 15
    },
    {
        id: "4",
        slug: "davidus-cigars-ashton",
        name: "Davidus Cigars- Ashton",
        city: "Ashton",
        stateabb: "MD",
        state: "Maryland",
        zip: "20861",
        address: "25 Olney Sandy Spring Rd, Ashton, MD 20861",
        phone: "(301) 260-0788",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        }, 
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: false, 
        hasPlasencia: true, 
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.149909,
        longitude: -77.013536,
        image: "/images/Davidus-Ashton/ashtonmdlounge.jpg",
        gallery: [
            "/images/Davidus-Ashton/ashtonmdlounge.jpg",
            "/images/Davidus-Ashton/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.4,
        reviewCount: 24,
    },
    {
        id: "5",
        slug: "broadleaf-tobacco",
        name: "Broadleaf Tobacco",
        city: "Severna Park",
        stateabb: "MD",
        state: "Maryland",
        zip: "21146",
        address: "487 Ritchie Hwy, Severna Park, MD 21146",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: false,
        hasAcid: false,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: false,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasPartagas: false,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: true,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Severna Park based Premium cigar shop with a comfortable lounge and curated humidor.",
        latitude: 39.083265,
        longitude: -76.549876,
        image: "/images/BLT/bltlounge1.jpg",
        gallery: [
            "/images/BLT/BLTlogo.png",
            "/images/BLT/BLTcrowd.jpg",
            "/images/BLT/bltlounge1.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 122,
    },
    {
        id: "6",
        slug: "aphelion-cigar-lounge",
        name: "Aphelion Cigar Lounge",
        city: "Gambrills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21054",
        address: "2510 Conway Rd, Gambrills, MD 21054",
        phone: "(410) 721-1700",
        website: "http://aphelioncigarlounge.com",
        hours: {
            mon: "10am - 12 AM",
            tue: "10am - 12 AM",
            wed: "10am - 12 AM",
            thu: "10am - 1 AM",
            fri: "10am - 2 AM",
            sat: "10am - 1 AM",
            sun: "10am - 12 AM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasCoffeeMaker: false,
        hasIceMaker: true,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Aphelion is the FIRST Black Owned cigar lounge and full bar to open in the state of Maryland. The founder(s) and owners James Price and Robert Monroe are true pioneers with nearly 15 years in this amazing industry.",
        latitude: 39.021416,
        longitude: -76.697973,
        image: "/images/aphelion/img1.jpg",
        gallery: [
            "/images/aphelion/img1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.1,
        reviewCount: 44,
    },
    {
        id: "7",
        slug: "titan-cigar",
        name: "Titan Cigar",
        city: "Gambrills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21054",
        address: "2634 Chapel Lake Dr, Gambrills, MD 21054",
        phone: "410-721-0100",
        website: "https://titancigar.com/",
        hours: {
            mon: "3 PM - 1 AM",
            tue: "3 PM - 1 AM",
            wed: "3 PM - 1 AM",
            thu: "3 PM - 1 AM",
            fri: "3 PM - 1 AM",
            sat: "3 PM - 1 AM",
            sun: "3 PM - 1 AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: false,
        description: "Visit us in The Village at Waugh Chapel, Gambrills, Maryland. We offer a wide variety of premium and hard-to-find cigars, as well as accessories like humidors, lighters, and cutters. Our friendly and knowledgeable staff are here to assist you with your selections.",
        latitude: 39.039779,
        longitude: -76.680763,
        image: "/images/titan/titanfront.jpg",
        gallery: [
            "/images/titan/titanfront.jpg"
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.1,
        reviewCount: 94,
    },
    {
        id: "8",
        slug: "davidus-cigars-towson",
        name: "Davidus Cigars- Towson",
        city: "Towson",
        stateabb: "MD",
        state: "Maryland",
        zip: "21204",
        address: "25 Allegheny Ave, Towson, MD 21204",
        phone: "(410) 616-9906",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.401555,
        longitude: -76.604001,
        image: "/images/towson/cl-towson-1.jpg",
        gallery: [
            "/images/towson/cl-towson-1.jpg",
            "/images/towson/towsonmgr.jpg",
            "/images/towson/cl-towson-10.jpg",
            "/images/towson/cl-towson-4.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "9",
        slug: "davidus-cigars-westminster",
        name: "Davidus Cigars- Westminster",
        city: "Westminster",
        stateabb: "MD",
        state: "Maryland",
        zip: "21157",
        address: "23 East Main Street, Westminster, MD 21157",
        phone: "(410) 876-4786",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.574814,
        longitude: -76.995304,
        image: "/images/westminster/cl-westminster-1.jpg",
        gallery: [
            "/images/westminster/wedsite-managerWES.jpg",
            "/images/westminster/cl-westminster-8.jpg",
            "/images/westminster/cl-westminster-4.jpeg",
            "/images/westminster/cl-westminster-1.jpg"

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "10",
        slug: "davidus-cigars-frederick",
        name: "Davidus Cigars- Frederick",
        city: "Frederick",
        stateabb: "MD",
        state: "Maryland",
        zip: "21071",
        address: "​529 West South Street, Frederick, MD 21157",
        phone: "301-662-6606",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.4127,
        longitude: -77.42426,
        image: "/images/frederick/cl-frederick-7.jpg",
        gallery: [
            "/images/frederick/Frederick-manager.jpg",
            "/images/frederick/cl-frederick-3.jpg",
            "/images/frederick/cl-frederick-1.jpg",
            "/images/frederick/cl-frederick-7.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "11",
        slug: "davidus-cigars-urbana",
        name: "Davidus Cigars- Urbana",
        city: "Urbana",
        stateabb: "MD",
        state: "Maryland",
        zip: "21704",
        address: "8925 Fingerboard Road, Urbana, MD 21704",
        phone: "301-874-1100",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.325074,
        longitude: -77.348089,
        image: "/images/urbana/cl-urbanasouthfrederick-1.jpg",
        gallery: [
            "/images/urbana/cl-urbanasouthfrederick-6.jpg",
            "/images/urbana/wedsite-managerURB.jpg",
            "/images/urbana/cl-urbanasouthfrederick-9.jpg",
            "/images/urbana/cl-urbanasouthfrederick-1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "12",
        slug: "davidus-cigars-shady-grove",
        name: "Davidus Cigars- Shady Grove",
        city: "Shady Grove",
        stateabb: "MD",
        state: "Maryland",
        zip: "20877",
        address: "15922 Shady Grove Road, Gaithersburg, MD 20877",
        phone: "301-963-8400",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: false, 
        hasPlasencia: true, 
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.118357,
        longitude: -77.183874,
        image: "/images/shady/cl-shadygroveroad-14.jpg",
        gallery: [
            "/images/shady/cl-shadygroveroad-manager-bc-jen.jpg",
            "/images/shady/cl-shadygroveroad-4.jpg",
            "/images/shady/cl-shadygroveroad-14.jpg",
            "/images/shady/cl-shadygroveroad-7.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "13",
        slug: "davidus-cigars-owings-mills",
        name: "Davidus Cigars- Owings Mills",
        city: "Owings Mills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21117",
        address: "10810 Reisterstown Road, Owings Mills, MD 21117",
        phone: "443-449-5871",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: false,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.118357,
        longitude: -77.183894,
        image: "/images/owings/cl-owingsmills-2.jpg",
        gallery: [
            "/images/owings/Owings_Mills-_Reisterstown.jpg",
            "/images/owings/img-2614_orig.jpg",
            "/images/owings/front",
            "/images/owings/cl-owingsmills-2.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.7,
        reviewCount: 70,
    },
    {
        id: "14",
        slug: "davidus-cigars-baltimore-little-italy",
        name: "Davidus Cigars- Baltimore (Little Italy)",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21231",
        address: "1300 Bank Street (Central Ave), Baltimore, MD 21231",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: false,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: false, 
        hasPlasencia: true, 
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.286622,
        longitude: -76.598793,
        image: "/images/Daviduslittleitaly/image_10.jpg",
        gallery: [
            "/images/Daviduslittleitaly/image_6.jpg.jpg",
            "/images/Daviduslittleitaly/wedsite-manageritaly.jpeg",
            "/images/Daviduslittleitaly/image_10.jpg",
            "/images/Daviduslittleitaly/image_13.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "15",
        slug: "davidus-cigars-rockville",
        name: "Davidus Cigars- Rockville",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "20852",
        address: "11632 Rockville Pike, Rockville, MD 20852",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: false,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        latitude: 39.048158,
        longitude: -77.114255,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/rockville/cl-rockvillepike-1.jpg",
        gallery: [
            "/images/rocvkille/wedsite-managerROC_copy.jpg",
            "/images/rockville/cl-rockvillepike-1.jpg",
            "/images/rockville/cl-rockvillepike-4.jpg",
            "/images/rockville/cl-rockvillepike-7.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "16",
        slug: "davidus-cigars-eldersburg",
        name: "Davidus Cigars- Eldersburg",
        city: "Eldersburg",
        stateabb: "MD",
        state: "Maryland",
        zip: "21784",
        address: "11716 Liberty Road, Eldersburg, MD 21784",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: false,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: false,
        hasLaAurora: false,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: false,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: true,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.396577,
        longitude: -76.922275,
        image: "/images/eldersburg/cl-eldersburg-7.jpg",
        gallery: [
            "/images/eldersburg/cl-eldersburg-7.jpg",
            "/images/eldersburg/eldersburg-manager.jpg",
            "/images/eldersburg/front.jpg",
            "/images/eldersburg/cl-eldersburg-5.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },{
        id: "17",
        slug: "tobacco-leaf",
        name: "Tobacco Leaf",
        city: "Jessup",
        stateabb: "MD",
        state: "Maryland",
        zip: "20794",
        address: "7395 Cedar Ave, Jessup, MD 20794",
        phone: "(239) 495-9296",
        website: "http://www.tobaccoleafmd.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Tobacco Leaf is a multi-generational family owned brick and mortar shop that specializes in luxury tobacco and the finest smoking accessories. It’s humble beginnings can be traced back to 1982, when Harish Gupta opened a small 700 square foot store in Hunt Valley, MD.",
        latitude: 39.16826,
        longitude: -76.790209,
        image: "/images/tobaccoleaf/front.jpg",
        gallery: [
            "/images/tobaccoleaf/DSC_0756.jpg",
            "/images/tobaccoleaf/DSC_0837.jpg",
            "/images/tobaccoleaf/front.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "18",
        slug: "chesapeake-pipe-and-cigar",
        name: "Chesapeake Pipe & Cigar",
        city: "Annapolis",
        stateabb: "MD",
        state: "Maryland",
        zip: "21401",
        address: "45 Old Solomons Island Rd, Annapolis, MD 21401",
        phone: "(443) 949-9004",
        website: "http://www.chesapeakepipeandcigar.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
                    ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "19",
        slug: "the-qg-cigar-lounge",
        name: "The QG Cigar Lounge",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21202",
        address: " 31 S Calvert St, Baltimore, MD 21202",
        phone: "(443) 949-9004",
        website: "https://www.theqg.com/pages/cigar-lounge-at-the-qg",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "20",
        slug: "legacy-cigar-lounge",
        name: "Legacy Cigar Lounge",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21206",
        address: "6333 Belair Rd, Baltimore, MD 21206",
        phone: "(443) 949-9004",
        website: "https://legacycigarlounge.com/?utm_source=chatgpt.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "21",
        slug: "burn-one-cigar-lounge",
        name: "Burn One Cigar Lounge",
        city: "Annapolis",
        stateabb: "MD",
        state: "Baltimore",
        zip: "21229",
        address: "5308 Edmondson Ave, Baltimore, MD 21229",
        phone: "(443) 949-9004",
        website: "https://www.burnonecigarlounge.com/",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "22",
        slug: "mt-vernon-cigars",
        name: "Mt Vernon Cigars",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21201",
        address: "221 W Read St, Baltimore, MD 21201",
        phone: "(443) 949-9004",
        website: "http://www.chesapeakepipeandcigar.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "23",
        slug: "glass-door-lounge",
        name: "Glass Door Lounge",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21202",
        address: "1263 E Fayette St, Baltimore, MD 21202",
        phone: "(443) 949-9004",
        website: "https://glass-door-lounge.edan.io/",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "24",
        slug: "club-house-cigar",
        name: "Club House Cigar",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21218",
        address: "2437 St Paul St, Baltimore, MD 21218",
        phone: "(443) 949-9004",
        website: "",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "25",
        slug: "bemore-smoke-place",
        name: "BeMore Smoke Place",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21231",
        address: "1724 Aliceanna St, Baltimore, MD 21231",
        phone: "",
        website: "",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "26",
        slug: "spartan-cigar-lounge",
        name: "Spartan Cigar Lounge",
        city: "Elkton",
        stateabb: "MD",
        state: "Maryland",
        zip: "21231",
        address: "Elkton MD 21231",
        phone: "",
        website: "",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "27",
        slug: "dan-cigar-lounge",
        name: "Dan's Cigar Lounge",
        city: "Rosedale",
        stateabb: "MD",
        state: "Maryland",
        zip: "21237",
        address: "8300-B Pulaski Hwy, Rosedale, MD 21237",
        phone: "(410) 780-5959",
        website: "https://danscigarlounge.com/?utm_source=chatgpt.com",
        hours: {
            mon: "10am - 9 PM",
            tue: "10am - 9 PM",
            wed: "10am - 9 PM",
            thu: "10am - 9 PM",
            fri: "10am - 11 PM",
            sat: "10am - 11 PM",
            sun: "11am - 7 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/chesapeakeMD/img1.png",
        gallery: [
            "/images/chesapeakeMD/img1.png",
            "/images/chesapeakeMD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.2,
        reviewCount: 102,
    },
    {
        id: "28",
        slug: "tinder-box",
        name: "Tinder Box",
        city: "Waldorf",
        stateabb: "MD",
        state: "Maryland",
        zip: "20601",
        address: "2754 Crain Highway, Waldorf, MD 20601",
        phone: "(410) 780-5959",
        website: "http://www.tinderboxinternational.com/store_pages/p3828.htm",
        hours: {
            mon: "10am - Midnight",
            tue: "10am - Midnight",
            wed: "10am - Midnight",
            thu: "10am - 1 AM",
            fri: "10am - 2 AM",
            sat: "9am - 2 AM",
            sun: "10am - Midnight"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: true,
        hasFuente: true,
        hasOpusX: true,
        hasRareOpusX: true,
        hasAshton: true,
        hasDiamond: true,
        hasAroma: true,
        hasDavidoff: true,
        hasAvo: true,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: false,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: true,
        hasLordByron: true,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: true,
        hasMacanudo: true,
        hasGurkha: true,
        hasPartagas: true,
        hasLaAurora: true,
        hasPlasencia: true,
        hasAganorsa: true,
        hasMemberLocker: true,
        sellsFood: false,
        sellsDrink: true,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: true,
        hasLiveMusic: false,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Great cigar lounge",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "/images/tinderMD/i.jpg",
        gallery: [
            "/images/tinderMD/i.jpg",
            
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 102,
    },
];