import type { Shop } from "./types";

export const massachussettsShops: Shop[] = [
    {
        id: "1",
        slug: "boston-cigar-lounge",
        name: "Boston Cigar Lounge",
        city: "Boston",
        stateabb: "MA",
        state: "Massachussetts",
        zip: "02129",
        address: "73 Main St, Boston, MA 02129",
        phone: "(617) 242-6010",
        website: "https://bostoncigarclub.com",
        hours: {
            mon: "3PM - 1AM",
            tue: "3PM - 1AM",
            wed: "3PM - 1AM",
            thu: "3PM - 1AM",
            fri: "3PM - 1AM",
            sat: "3PM - 1AM",
            sun: "3PM - 1AM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Discover an unparalleled escape at Boston Cigar Club & Shop, a sophisticated destination where the worlds of premium cigars, exquisite spirits, and gourmet cuisine unite. Explore our extensive selection of fine tobacco in the dedicated cigar shop, boasting its own humidor. Then, unwind in our refined lounge, featuring a …",
        latitude: 42.373532,
        longitude: -71.061562,
        image: "/images/bostoncigar/bostonlounge1.jpg",
        gallery: [
            "/images/bostoncigar/bostonlounge1.jpg",
            "/images/bostoncigar/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
    },
    ]