import type { Shop } from "./types";

export const michiganShops: Shop[] = [
    {
        id: "1",
        slug: "la-casa-cigars-and-lounge",
        name: "La Casa Cigars and Lounge",
        city: "Detroit",
        stateabb: "MI",
        state: "Michigan",
        zip: "48266",
        address: "1502 Randolph St, Detroit, MI 48226",
        phone: "(313) 285-8332",
        website: "http://www.lacasacigars.com",
        hours: {
            mon: "10AM - Midnight",
            tue: "10AM - Midnight",
            wed: "10AM - Midnight",
            thu: "10AM - 1AM",
            fri: "10AM - 2AM",
            sat: "10AM - 2AM",
            sun: "Noon - 12:30AM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "WELCOME TO Cigar Sanctuary",
        latitude: 42.33664,
        longitude: -83.046024,
        image: "/images/lacasaMI/img1.jpg",
        gallery: [
            "/images/lacasaMI/img1.jpg",
            "/images/lacasaMI/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]