import type { Shop } from "./types";

export const minnesotaShops: Shop[] = [
    {
        id: "1",
        slug: "anthony-pipe-and-cigar-lounge",
        name: "Anthony's Pipe & Cigar Lounge",
        city: "Minneapolis",
        stateabb: "MN",
        state: "Minnesota",
        zip: "55408",
        address: "907 W Lake St, Minneapolis, MN 55408",
        phone: "(612) 345-4388",
        website: "",
        hours: {
            mon: "10 AM-10 PM",
            tue: "10 AM-10 PM",
            wed: "10 AM-10 PM",
            thu: "10 AM-10 PM",
            fri: "10 AM-10 PM",
            sat: "10 AM-10 PM",
            sun: "11AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 44.94659,
        longitude: -93.288292,
        image: "/images/anthonyMN/img1.jpg",
        gallery: [
            "/images/anthonyMN/img1.jpg",
            "/images/anthonyMN/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]