import type { Shop } from "./types";

export const missouriShops: Shop[] = [
    {
        id: "1",
        slug: "leatherwood",
        name: "LEATHERWOOD Handmade Cigars",
        city: "Saint James",
        stateabb: "MO",
        state: "Missouri",
        zip: "65559",
        address: "115 W springfield ST, Saint james, Missouri 65559",
        phone: "(907) 274-7473",
        website: "http://leatherwoodstjames.com",
        hours: {
            mon: "Closed",
            tue: "Closed",
            wed: "Closed",
            thu: "11 AM-8 PM",
            fri: "11 AM-8 PM",
            sat: "11 AM-8 PM",
            sun: "11 AM-8 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "LEATHERWOOD Handmade Cigars is an internationally acclaimed luxury cigar lounge and curated humidor in St. James, Missouri. ",
        latitude: 37.997468,
        longitude: -91.615353,
        image: "/images/leatherwoodMO/img1.jpg",
        gallery: [
            "/images/leatherwoodMO/img1.jpg",
            "/images/leatherwoodMO/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]