import type { Shop } from "./types";

export const mississippiShops: Shop[] = [
    {
        id: "1",
        slug: "signature-bar-and-cigar-lounge",
        name: "Signature Bar & Cigar Lounge",
        city: "D'Iberville",
        stateabb: "MS",
        state: "Mississippi",
        zip: "39540",
        address: "3516 Sangani Blvd, D'Iberville, MS 39540",
        phone: "(228) 967-7625",
        website: "https://signature-bar-cigar-lounge.ueniweb.com",
        hours: {
            mon: "Noon- 11PM",
            tue: "Noon- 11PM",
            wed: "Noon- Midnight",
            thu: "Noon- 3AM",
            fri: "Noon- 3AM",
            sat: "Noon- 3AM",
            sun: "Noon- 10PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 30.459119,
        longitude: -88.892095,
        image: "/images/shops/signatureMS/img1.jpg",
        gallery: [
            "/images/shops/signatureMS/img1.jpg", 
            "/images/shops/signatureMS/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]