import type { Shop } from "./types";

export const nebraskaShops: Shop[] = [
    {
        id: "1",
        slug: "safari-cigars-and-lounge",
        name: "Safari Cigars and Lounge",
        city: "Omaha",
        stateabb: "NE",
        state: "Nebraska",
        zip: "68164",
        address: "13110 Birch Dr, Omaha, NE 68164",
        phone: "(402) 965-1460",
        website: "  http://www.safaricigarsandlounge.com",
        hours: {
            mon: "9AM - Midnight",
            tue: "9AM - Midnight",
            wed: "9AM - Midnight",
            thu: "9AM - Midnight",
            fri: "9AM - Midnight",
            sat: "9AM - Midnight",
            sun: "11:45AM - 10:30PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Creating the most unique and pleasurable cigar smoking experience in Omaha.",
        latitude: 41.291113,
        longitude: -96.119094,
        image: "/images/safarine/img1.jpg",
        gallery: [
            "/images/safarine/img1.jpg",
            "/images/safarine/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]