import type { Shop } from "./types";

export const nevadaShops: Shop[] = [
    {
        id: "1",
        slug: "montecristo-cigar-bar",
        name: "Montecristo Cigar Bar",
        city: "Las Vegas",
        stateabb: "NV",
        state: "Nevada",
        zip: "89109",
        address: "3655 Las Vegas Blvd S, Las Vegas, NV 89109",
        phone: "(877) 796-2096",
        website: "https://www.caesars.com/paris-las-vegas/things-to-do/nightlife/montecristo-cigar-bar",
        hours: {
            mon: "11AM - 1AM",
            tue: "11AM - 1AM",
            wed: "11AM - 1AM",
            thu: "11AM - 1AM",
            fri: "11AM - 1AM",
            sat: "11AM - 1AM",
            sun: "11AM - 1AM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 36.112243,
        longitude: -115.17042,
        image: "/images/montenv/image.jpg",
        gallery: [
            "/images/montenv/image.jpg",

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    ]