import type { Shop } from "./types";

export const newhampshireShops: Shop[] = [
    {
        id: "1",
        slug: "cigar-shenanigans-cigar-and-cocktail-lounge",
        name: "Cigar Shenanigans Cigar & Cocktail Lounge",
        city: "North Conway",
        stateabb: "NH",
        state: "New Hampshire",
        zip: "03860",
        address: "1903 White Mountain Hwy, North Conway, NH 03860",
        phone: "(603) 307-1036",
        website: "",
        hours: {
            mon: "11AM - 1AM",
            tue: "11AM - 1AM",
            wed: "11AM - 1AM",
            thu: "11AM - 1AM",
            fri: "11AM - 1AM",
            sat: "11AM - 1AM", 
            sun: "11AM - 11PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Friends, fun, tomfoolery, entertainment, relaxation, adult beverages, and premium cigars. Definitely not your average cigar lounge!!",
        latitude: 44.031324,
        longitude: -71.119992,
        image: "/images/cigarNH/img1.jpg",
        gallery: [
            "/images/cigarNH/1.jpg",
            "/images/cigarNH/2.jpg",
            
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]