import type { Shop } from "./types";

export const newjerseyShops: Shop[] = [
    {
        id: "1",
        slug: "10-north-lounge",
        name: "10 North Lounge",
        city: "Atlantic City",
        stateabb: "NJ",
        state: "New Jersey",
        zip: "08401",
        address: "2831 Boardwalk, Atlantic City, NJ 08401",
        phone: "(800) 843-8767",
        website: "https://www.caesars.com › tropicana-ac › things-to-do › nightlife",
        hours: {
            mon: "24 hours",
            tue: "24 hours",
            wed: "24 hours",
            thu: "24 hours",
            fri: "24 hours",
            sat: "24 hours",
            sun: "24 hours",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Sophisticated and upscale, sip top-shelf libations and stay close to the action with bar-top gaming, or get cozy around our statement double-sided fireplace.",
        latitude: 39.352361,
        longitude: -74.445377,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]