import type { Shop } from "./types";

export const newyorkShops: Shop[] = [
    {
        id: "1",
        slug: "casa-de-montecristo-cigar-lounge",
        name: "Casa de Montecristo Cigar Lounge",
        city: "New York City",
        stateabb: "NY",
        state: "New York",
        zip: "10022",
        address: "1016 2nd Ave, New York, NY 10022",
        phone: "(212) 750-0809",
        hours: {
            mon: "11AM - 11PM",
            tue: "11AM - 11PM",
            wed: "11AM - 11PM", 
            thu: "11AM - 11PM",
            fri: "11AM - 11PM",
            sat: "11AM - 11PM",
            sun: "11AM - 11PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Casa De Montecristo New York – one of the finest cigar lounges in NYC. With its superb stogie collection, you’re guaranteed to find a cigar brand, type and size that meets your needs. Don’t worry if you’re a complete novice when it comes to cigars. Simply have a chat with a member of our onsite friendly and educated team.",
        latitude: 40.757073,
        longitude: -73.966604,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
    },
    ]