import type { Shop } from "./types";

export const northcarolinaShops: Shop[] = [
    {
        id: "1",
        slug: "tapp-that-ash-cigar-bar-and-lounge",
        name: "Tapp That Ash Cigar Bar & Lounge",
        city: "Franklington",
        stateabb: "NC",
        state: "North Carolina",
        zip: "27525",
        address: "22 S Main St, Franklinton, NC 27525",
        phone: "(919) 728-8106",
        website: "https://tappthatash.com",
        hours: {
            mon: "4PM - 10PM",
            tue: "4PM - 10PM",
            wed: "2PM - 10PM",
            thu: "2PM - 10PM",
            fri: "2PM - Midnight",
            sat: "2PM - Midnight",
            sun: "Noon - 8PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Franklinton's premiere cigar & Bourbon Lounge.",
        latitude: 36.103023,
        longitude: -78.457354,
        image: "/images/tappthatnc/img1.jpg",
        gallery: [
            "/images/tappthatnc/img1.jpg",
            "/images/tappthatnc/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "2",
        slug: "salem-street-cigar-lounge",
        name: "Salem Street Cigar Lounge",
        city: "Apex",
        stateabb: "NC",
        state: "North Carolina",
        zip: "27502",
        address: "1510 N Salem St, Apex, NC 27502",
        phone: "(919) 355-2006",
        website: "http://www.salemstreetcigarlounge.com",
        hours: {
            mon: "10AM - 9PM",
            tue: "10AM - 9PM",
            wed: "10AM - 9PM",
            thu: "10AM - 9PM",
            fri: "10AM - 10PM",
            sat: "10AM - 10PM",
            sun: "10AM - 9PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: true,
        hasPipeTobacco: true,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Salem Street Pub has established itself as a neighborhood favorite! Perfect for the whole family or an evening out on the town!",
        latitude: 35.748893,
        longitude: -78.851056,
        image: "/images/salemNC/img1.jpg",
        gallery: [
            "/images/salemNC/img1.jpg",
            "/images/salemNC/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.1,
        reviewCount: 1123,
    },
    {
        id: "3",
        slug: "tobacoonists-of-cary",
        name: "Tobacconists of Cary",
        city: "Cary",
        stateabb: "NC",
        state: "North Carolina",
        zip: "27502",
        address: "2434 SW Cary Pkwy, Cary, NC 27513",
        phone: "(919) 469-4262",
        website: "http://www.salemstreetcigarlounge.com",
        hours: {
            mon: "11AM - 6PM",
            tue: "11AM - 6PM",
            wed: "11AM - 6PM",
            thu: "11AM - 6:30PM",
            fri: "11AM - 6:30PM",
            sat: "11AM - 5:30PM",
            sun: "1PM - 5PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: true,
        hasPipeTobacco: true,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "They've got every brand you could imagine, I've never gotten a bad cigar from these guys.",
        latitude: 35.763721,
        longitude: -78.820413,
        image: "/images/caryNC/img1.jpg",
        gallery: [
            "/images/caryNC/img1.jpg",

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.1,
        reviewCount: 1123,
    },
    ]