import type { Shop } from "./types";

export const ohioShops: Shop[] = [
    {
        id: "1",
        slug: "pipes-and-pleasures-cigar-lounge",
        name: "Pipes & Pleasures Cigar Lounge",
        city: "Columbus",
        stateabb: "OH",
        state: "Ohio",
        zip: "432132",
        address: "4244 E Main St, Columbus, OH 43213",
        phone: "(614) 616-1000",
        website: "http://www.facebook.com › LuvOurPipesandCigars",
        hours: {
            mon: "10:30AM -8 PM",
            tue: "10:30AM -8 PM",
            wed: "10:30AM -8 PM",
            thu: "10:30AM -8 PM",
            fri: "10:30AM -8 PM",
            sat: "10:30AM -8 PM",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Premium Cigars and much more at Pipes & Pleasures..",
        latitude: 39.95601,
        longitude: -82.885167,
        image: "/images/shops/pipesOH/img1.jpg",
        gallery: [
            "/images/shops/pipesOH/img1.jpg",
            "/images/shops/pipesOH/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]