import type { Shop } from "./types";

export const oklahomaShops: Shop[] = [
    {
        id: "1",
        slug: "ash-cigar-lounge",
        name: "ASH Cigar Lounge",
        city: "Oklahoma City",
        stateabb: "OK",
        state: "Oklahoma",
        zip: "73102",
        address: "712 N Broadway Ave, Oklahoma City, OK 73102",
        phone: "(405) 673-7452",
        website: "http://www.ashcigarloungeokc.com",
        hours: {
            mon: "Noon - 10PM",
            tue: "Noon - 10PM",
            wed: "Noon - Midnight",
            thu: "Noon - Midnight",
            fri: "Noon - Midnight",
            sat: "Noon - Midnight",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Enjoy a wide selection of cigars from our humidor or bring your own.",
        latitude: 35.474585,
        longitude: -97.513847,
        image: "/images/shops/ashOK/img1.jpg",
        gallery: [
            "/images/shops/ashOK/img1.jpg",
            "/images/shops/ashOK/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]