import type { Shop } from "./types";

export const oregonShops: Shop[] = [
    {
        id: "1",
        slug: "cigars-on-seventh",
        name: "Cigars on 7th",
        city: "Lacey",
        stateabb: "OR",
        state: "Oregon",
        zip: "97401",
        address: "679 Lincoln St, Eugene, OR 97401",
        phone: "(541) 654-5004",
        website: "https://cigarson7th.com",
        hours: {
            mon: "10AM - 7PM",
            tue: "10AM - 7PM",
            wed: "10AM - 7PM",
            thu: "10AM - 7PM",
            fri: "10AM - 7PM",
            sat: "10AM - 7PM",
            sun: "10AM - 3PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "We Believe that wanting the best should never get in the way of wanting to relax..",
        latitude: 44.052408,
        longitude: -123.097094,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]