import type { Shop } from "./types";

export const pennsylvaniaShops: Shop[] = [
    {
        id: "1",
        slug: "ashton-cigar-bar",
        name: "Ashton Cigar Bar",
        city: "Philadelphia",
        stateabb: "PA",
        state: "Pennsylvania",
        zip: "19102",
        address: "1522 Walnut St, Philadelphia, PA 19102",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: {
            mon: "4pm - 11PM",
            tue: "4pm - 11PM",
            wed: "4pm - 11PM",
            thu: "4pm - 11PM", 
            fri: "4pm - 11PM", 
            sat: "4pm - 11PM",
            sun: "4pm - 11PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "Modern, upscale cigar lounge and cocktail bar with an extensive menu of whiskey, cocktails, spirits, and cigars. Located above Holt’s Cigar Shop in downtown Philadelphia. You can still purchase cigars from the Holt's Cigar Shop online and in store.",
        latitude: 39.949464,
        longitude: -75.167106,
        image: "/images/ashtonpa/ashtonpa1.jpg",
        gallery: [
            "/images/ashtonpa/ashtonpa1.jpg",
            "/images/ashtonpa/logo.svg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.1,
        reviewCount: 1123,
    },
    {
        id: "2",
        slug: "cigars-international-superstore-hamburg",
        name: "Cigars International Superstore",
        city: "Behtlehem",
        stateabb: "PA",
        state: "Pennsylvania",
        zip: "19526",
        address: "1635 Mountain Rd, Hamburg, PA 19526",
        phone: "(610) 562-0500",
        website: "https://www.cigarsinternational.com",
        hours: {
            mon: "9AM - 8PM",
            tue: "9AM - 10PM",
            wed: "9AM - 1PM",
            thu: "9AM - Midnight",
            fri: "9AM - Midnight",
            sat: "9AM - Midnight",
            sun: "10AM - 8PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: false,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: false,
        hasDavidoff: true,
        hasAvo: false,
        hasLiga: false,
        hasAcid: false,
        hasTatuaje: false,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessory: true,
        description: "With three locations in the Sarasota, Florida area, Cigar Cigars offers a premium cigar experience built on decades of expertise. Established in 1995, we grew to become one of the largest cigar retailers in the Philadelphia region before bringing our passion for cigars to Florida in 2020. Today, we are proud to call Sarasota home.",
        latitude: 40.560164,
        longitude: -76.005147,
        image: "/images/CIPA/1.jpg",
        gallery: [
            "/images/CIPA/1.jpg",
            "/images/CIPA/3.jpg",
            "/images/CIPA/2.jpg",
            "/images/CIPA/4.png",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.2,
        reviewCount: 102,
    },
    ]