import type { Shop } from "./types";

export const rhodeislandShops: Shop[] = [
    {
        id: "1",
        slug: "white-ash-cigar-lounge",
        name: "White Ash Cigar Lounge",
        city: "Pawtucket",
        stateabb: "RI",
        state: "Rhode Island",
        zip: "02861",
        address: "413 Central Ave, Pawtucket, RI 02861",
        phone: "(401) 726-1715",
        website: "https://whiteashcigarlounge.com",
        hours: {
            mon: "Noon - Midnight",
            tue: "11AM - Midnight",
            wed: "11AM - Midnight",
            thu: "11AM - 1 AM",
            fri: "11AM - 1 AM",
            sat: "11AM - 1 AM", 
            sun: "Noon - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Nestled in the heart of Pawtucket, our sophisticated cigar lounge strikes the perfect balance between refined elegance and welcoming comfort..",
        latitude: 41.884641,
        longitude: -71.365507,
        image: "/images/shops/whiteashRI/img1.png",
        gallery: [
            "/images/shops/whiteashRI/img1.png",
            "/images/shops/whiteashRI/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]