import type { Shop } from "./types";

export const southcarolinaShops: Shop[] = [
    {
        id: "1",
        slug: "lite-um-up-cigars-lounge",
        name: "LITE UM UP CIGARS LOUNGE",
        city: "Columbia",
        stateabb: "SC",
        state: "South Carolina",
        zip: "29229",
        address: "4435 Hard Scrabble Rd, Columbia, SC 29229",
        phone: "(803) 708-4877",
        website: "http://liteumupcigars.net",
        hours: {
            mon: "11AM - 8PM",
            tue: "11AM - 8PM",
            wed: "11AM - 8PM",
            thu: "11AM - 8PM",
            fri: "11AM - 9PM",
            sat: "11AM - 9PM",
            sun: "Noon - 7PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "WE ALWAYS HAVE A PLACE FOR YOU HERE AT LITE UM UP CIGARS",
        latitude: 34.146271,
        longitude: -80.911674,
        image: "/images/liteemsc/img1.jpg",
        gallery: [
            "/images/liteemsc/img1.jpg",
            "/images/liteemsc/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]