import type { Shop } from "./types";

export const southdakotaShops: Shop[] = [
    {
        id: "1",
        slug: "deadwood-tobacco-co-and-cigar-bar",
        name: "Deadwood Tobacco Co. and Cigar Bar",
        city: "Deadwood",
        stateabb: "SD",
        state: "South Dakota",
        zip: "57732",
        address: "715 Main St, Deadwood, SD 57732",
        phone: "(605) 722-1510",
        website: "http://www.deadwoodtobacco.com",
        hours: {
            mon: "10AM- 6PM",
            tue: "10AM- 6PM",
            wed: "10AM- 6PM",
            thu: "10AM- 10PM",
            fri: "10 AM- Midnight",
            sat: "10 AM- Midnight",
            sun: "10AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The new Deadwood Tobacco is at 715 Main Street featuring the largest humidor in the state, a 6,000 sq. ft. lounge and venue, an immerse bar with the best local and regional taps.",
        latitude: 44.375491,
        longitude: -103.731411,
        image: "/images/deadwoodSD/img1.jpg",
        gallery: [
            "/images/deadwoodSD/img1.jpg",
            "/images/deadwoodSD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]