import type { Shop } from "./types";

export const tennesseeShops: Shop[] = [
    {
        id: "1",
        slug: "casa-de-montecristo-cigar-lounge",
        name: "Casa de Montecristo Cigar Lounge",
        city: "Nashville",
        stateabb: "TN",
        state: "Tennessee",
        zip: "37203",
        address: "600 9th Ave S, Nashville, TN 37203",
        phone: "(615) 800-3397",
        website: "https://www.casademontecristo.com/nashville/?utm_source=partnerize&utm_medium=affiliate&utm_campaign=21181&utm_content=8-12854&clickId=5452823406",
        hours: {
            mon: "11AM - 8PM",
            tue: "11AM - 8PM",
            wed: "11AM - 8PM",
            thu: "11AM - 8PM",
            fri: "11AM - 9PM",
            sat: "11AM - 9PM",
            sun: "Noon - 7PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "There’s always something happening at Casa de Montecristo, the premier destination for premium cigars and elevated cigar lounge experiences. From exclusive cigar tastings to signature events, this is your hub for everything happening at Casa.",
        latitude: 36.151613,
        longitude: -86.7799,
        image: "/images/casatn/img1.jpg",
        gallery: [
            "/images/casatn/img1.jpg",
            "/images/casatn/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]