import type { Shop } from "./types";

export const texasShops: Shop[] = [
    {
        id: "1",
        slug: "habana-house-cigar-lounge-south-austin",
        name: "Habana House Cigar Lounge South Austin",
        city: "Austin",
        stateabb: "TX",
        state: "Texas",
        zip: "78704",
        address: "3601 S Congress Ave, Austin, TX 78704",
        phone: "(512) 447-9449",
        website: "http://www.habanahousecigarlounge.com",
        hours: {
            mon: "10AM- 830PM",
            tue: "10AM- 830PM",
            wed: "10AM- 830PM",
            thu: "10AM- 830PM",
            fri: "10AM- 10PM",
            sat: "10AM- 10PM", 
            sun: "Noon- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Habana House Cigar Lounge is a well-established haven for cigar enthusiasts, proudly serving our community for 25 years. With two inviting lounges and a third on the horizon, we offer a sophisticated atmosphere for aficionados to relax, connect, and enjoy premium cigars. ",
        latitude: 30.227653,
        longitude: -97.760545,
        image: "/images/habanaTX/img1.jpg",
        gallery: [
            "/images/habanaTX/img1.jpg",
            "/images/habanaTX/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    ]