import type { Shop } from "./types";

export const vermontShops: Shop[] = [
    {
        id: "1",
        slug: "garcias-tobacco-shop",
        name: "Garcia's Tobacco Shop",
        city: "Burlington",
        stateabb: "VT",
        state: "Vermont",
        zip: "05401",
        address: "97 Church St, Burlington, VT 05401",
        phone: "(802) 658-5737",
        website: "http://www.garciatobaccoshop.com",
        hours: {
            mon: "9AM - 10PM",
            tue: "9AM - 10PM",
            wed: "9AM - 10PM",
            thu: "9AM - 10PM",
            fri: "9AM - 10PM",
            sat: "9AM - 10PM", 
            sun: "9AM - 10PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "We are located in the heart of downtown Burlington on the Church Street Marketplace.",
        latitude: 44.477695,
        longitude: -73.212802,
        image: "/images/garcia/img1.jpg",
        gallery: [
            "/images/garcia/img1.jpg",
            
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]