import type { Shop } from "./types";

export const virginiaShops: Shop[] = [
    {
        id: "1",
        slug: "magoo-cigar-lounge",
        name: "Magoo's Cigar Lounge",
        city: "Norfolk",
        stateabb: "VA",
        state: "Virginia",
        zip: "60653",
        address: "246 E Main St, Norfolk, VA 23510",
        phone: "(757) 937-5047",
        website: "",
        hours: {
            mon: "11am - 8:30 PM",
            tue: "11am - 8:30 PM",
            wed: "11am - 8:30 PM",
            thu: "11am - 8:30 PM",
            fri: "11am - 10 PM",
            sat: "11am - 10 PM",
            sun: "12PM - 6 PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Magoo's Cigar Lounge is a Cigar shop located in Norfolk.",
        latitude: 42.37747,
        longitude: -71.06699,
        image: "/images/magoos/magooslogo.jpg",
        gallery: [
            "/images/magoos/magooslogo.jpg",
            "/images/magoos/lounge1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
    },
];