import type { Shop } from "./types";

export const westvirginiaShops: Shop[] = [
    {
        id: "1",
        slug: "the-squire-tobacoonist",
        name: "The Squire Tobacconist",
        city: "Charleston",
        stateabb: "WV",
        state: "West Virginia",
        zip: "25387",
        address: "104 Hills Plaza Charleston, WV 25387",
        phone: "(304) 345-0366",
        website: "ttp://www.thesquirewv.com",
        hours: {
            mon: "Closed",
            tue: "11AM - 6 PM",
            wed: "11AM - 6 PM",
            thu: "11AM - 6 PM",
            fri: "11AM - 6 PM",
            sat: "11AM - 4 PM",
            sun: "Closed",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "The Squire Tobacconist in Charleston, West Virginia has been part of the regional cigar community since the early 1990s, offering a place where customers can browse a large humidor, talk shop, or spend a quiet moment with a favorite smoke.",
        latitude: 38.367742,
        longitude: -81.668941,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]