import type { Shop } from "./types";

export const wisconsinShops: Shop[] = [
    {
        id: "1",
        slug: "appleton-cigar-co",
        name: "Appleton Cigar Co.",
        city: "Appleton",
        stateabb: "WI",
        state: "Wisconsin",
        zip: "54911",
        address: "415 W College Ave, Appleton, WI 54911",
        phone: "(920) 830-8349",
        website: "http://www.appletoncigar.com",
        hours: {
            mon: "11:30 AM-10:30 PM",
            tue: "11:30 AM-10:30 PM",
            wed: "11:30 AM-10:30 PM",
            thu: "11:30 AM-10:30 PM",
            fri: "11:30 AM-10:30 PM",
            sat: "11:30 AM-10:30 PM",
            sun: "11:30 AM-10:30 PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,
        hasFuente: true,
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "Appleton Souvenir & Cigar Co. (ASCC) opened on April 1st, 1997, as a souvenir, apparel, and small selection of premium cigar store under the ownership of Mary Weidert.",
        latitude: 44.261542,
        longitude: -88.411363,
        image: "/images/public/appletonWI/img1.jpg",
        gallery: [
            "/images/public/appletonWI/img1.jpg",
            "/images/public/appletonWI/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]