import type { Shop } from "./types";

export const wyomingShops: Shop[] = [
    {
        id: "1",
        slug: "the-colonel-venue-and-cigar-lounge",
        name: "The Colonel Venue and Cigar Lounge",
        city: "Great Falls",
        stateabb: "WY",
        state: "Wyoming",
        zip: "82414",
        address: "1328 Beck Ave, Cody, WY 82414",
        phone: "(307) 578-8510",
        website: "https://www.thecolonelvenue.com",
        hours: {
            mon: "Closed",
            tue: "Closed",
            wed: "Closed",
            thu: "6PM - 11PM",
            fri: "6PM - Midnight",
            sat: "6PM - Midnight",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadron: false,   
        hasOpusX: false,
        hasRareOpusX: false,
        hasAshton: true,
        hasDiamond: false,
        hasAroma: true,
        hasDavidoff: false,
        hasAvo: false,
        hasLiga: true,
        hasAcid: true,
        hasTatuaje: true,
        hasPerdomo: true,
        hasAlec: true,
        hasHoya: true,
        hasLFD: true,
        hasOliva: true,
        hasNub: true,
        hasCain: false,
        hasMyFather: true,
        hasCamacho: true,
        hasAJ: true,
        hasSanCristobal: true,
        hasAtabey: false,
        hasLordByron: false,
        hasGreyCliff: false,
        hasDunhill: false,
        hasHouseCigar: true,
        hasMontecristo: true,
        hasRomeo: true,
        hasHuppman: true,
        hasCAO: true,
        hasRP: true,
        hasCohiba: true,
        hasPunch: true,
        hasAging: false,
        hasMacanudo: true,
        hasGurkha: false,
        hasMemberLocker: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessory: true,
        description: "This warm environment features comfortable seating, stately furniture and a games table for those looking to enjoy a fun game of poker.",
        latitude: 47.505713,
        longitude: -111.300533,
        image: "/images/colWY/img1.jpg",
        gallery: [
            "/images/colWY/img1.jpg",
            "/images/colWY/img2.jpg"
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 32,
    },
    ]