import { PrismaClient } from "@prisma/client";
import { shops } from "../lib/shops";

const prisma = new PrismaClient();

async function main() {
    for (const shop of shops) {
        await prisma.shop.upsert({
            where: { slug: shop.slug },
            update: {
                name: shop.name,
                city: shop.city,
                state: shop.state,
                stateabb: shop.stateabb,
                zip: shop.zip,
                address: shop.address,
                phone: shop.phone,
                website: shop.website ?? null,
                description: shop.description,
                image: "image" in shop ? (shop as { image?: string }).image ?? null : null,
                hasLounge: shop.hasLounge,
                hasHumidor: shop.hasHumidor,                
                hasPadron: shop.hasPadron ?? false,
                hasFuente: shop.hasFuente ?? false,
                hasOpusX: shop.hasOpusX ?? false,
                hasRareOpusX: shop.hasRareOpusX ?? false,
                hasAshton: shop.hasAshton ?? false,
                hasDiamond: shop.hasDiamond ?? false,
                hasAroma: shop.hasAroma ?? false,
                hasDavidoff: shop.hasDavidoff ?? false,
                hasAvo: shop.hasAvo ?? false,
                hasLiga: shop.hasLiga ?? false,
                hasAcid: shop.hasAcid ?? false,
                hasTatuaje: shop.hasTatuaje ?? false,
                hasPerdomo: shop.hasPerdomo ?? false,
                hasAlec: shop.hasAlec ?? false,
                hasHoya: shop.hasHoya ?? false,
                hasLFD: shop.hasLFD ?? false,
                hasOliva: shop.hasOliva ?? false,
                hasNub: shop.hasNub ?? false,
                hasCain: shop.hasCain ?? false,
                hasMyFather: shop.hasMyFather ?? false,
                hasCamacho: shop.hasCamacho ?? false,
                hasAJ: shop.hasAJ ?? false,
                hasSanCristobal: shop.hasSanCristobal ?? false,
                hasAtabey: shop.hasAtabey ?? false,
                hasLordByron: shop.hasLordByron ?? false,
                hasGreyCliff: shop.hasGreyCliff ?? false,
                hasDunhill: shop.hasDunhill ?? false,
                hasHouseCigar: shop.hasHouseCigar ?? false,
                hasMontecristo: shop.hasMontecristo ?? false,
                hasRomeo: shop.hasRomeo ?? false,
                hasHuppman: shop.hasHuppman ?? false,
                hasCAO: shop.hasCAO ?? false,
                hasRP: shop.hasRP ?? false,
                hasCohiba: shop.hasAJ ?? false,
                hasPunch: shop.hasPunch ?? false,
                hasAging: shop.hasAging ?? false,
                hasMacanudo: shop.hasMacanudo ?? false,
                hasGurkha: shop.hasGurkha ?? false,
                hasMemberLockers: shop.hasMemberLockers ?? false,
                sellsFood: shop.sellsFood ?? false,
                hasPipeTobacco: shop.hasPipeTobacco ?? false,
                hasMemberAccess: shop.hasMemberAccess ?? false,
                hasHooka: shop.hasHooka ?? false,
                hasEvents: shop.hasEvents ?? false,
                hasLiquorLicense: shop.hasLiquorLicense ?? false,
                canBringInLiquor: shop.canBringInLiquor ?? false,
                hasInternetAccess: shop.hasInternetAccess ?? false,
                hasCoffeeMaker: shop.hasCoffeeMaker ?? false,
                hasIceMaker: shop.hasIceMaker ?? false,
                hasBigTV: shop.hasBigTV ?? false,
                sellsAccessories: shop.sellsAccessories,
                latitude: "latitude" in shop ? shop.latitude ?? null : null,
                longitude: "longitude" in shop ? shop.longitude ?? null : null,
                isFeatured: "isFeatured" in shop ? shop.isFeatured ?? false : false,
                isSponsored: "isSponsored" in shop ? shop.isSponsored ?? false : false,
            },
            create: {
                name: shop.name,
                slug: shop.slug,
                city: shop.city,
                state: shop.state,
                stateabb: shop.stateabb,
                zip: shop.zip,
                address: shop.address,
                phone: shop.phone,
                website: shop.website ?? null,
                description: shop.description,
                image: "image" in shop ? (shop as { image?: string }).image ?? null : null,
                hasLounge: shop.hasLounge,
                hasHumidor: shop.hasHumidor,
                hasPadron: shop.hasPadron ?? false,
                hasFuente: shop.hasFuente ?? false,
                hasOpusX: shop.hasOpusX ?? false,
                hasRareOpusX: shop.hasRareOpusX ?? false,
                hasAshton: shop.hasAshton ?? false,
                hasDiamond: shop.hasDiamond ?? false,
                hasAroma: shop.hasAroma ?? false,
                hasDavidoff: shop.hasDavidoff ?? false,
                hasAvo: shop.hasAvo ?? false,
                hasLiga: shop.hasLiga ?? false,
                hasAcid: shop.hasAcid ?? false,
                hasTatuaje: shop.hasTatuaje ?? false,
                hasPerdomo: shop.hasPerdomo ?? false,
                hasAlec: shop.hasAlec ?? false,
                hasHoya: shop.hasHoya ?? false,
                hasLFD: shop.hasLFD ?? false,
                hasOliva: shop.hasOliva ?? false,
                hasNub: shop.hasNub ?? false,
                hasCain: shop.hasCain ?? false,
                hasMyFather: shop.hasMyFather ?? false,
                hasCamacho: shop.hasCamacho ?? false,
                hasAJ: shop.hasAJ ?? false,
                hasSanCristobal: shop.hasSanCristobal ?? false,
                hasAtabey: shop.hasAtabey ?? false,
                hasLordByron: shop.hasLordByron ?? false,
                hasGreyCliff: shop.hasGreyCliff ?? false,
                hasDunhill: shop.hasDunhill ?? false,
                hasHouseCigar: shop.hasHouseCigar ?? false,
                hasMontecristo: shop.hasMontecristo ?? false,
                hasRomeo: shop.hasRomeo ?? false,
                hasHuppman: shop.hasHuppman ?? false,
                hasCAO: shop.hasCAO ?? false,
                hasRP: shop.hasRP ?? false,
                hasCohiba: shop.hasAJ ?? false,
                hasPunch: shop.hasPunch ?? false,
                hasAging: shop.hasAging ?? false,
                hasMacanudo: shop.hasMacanudo ?? false,
                hasGurkha: shop.hasGurkha ?? false,
                hasMemberLockers: shop.hasMemberLockers ?? false,
                sellsFood: shop.sellsFood ?? false,
                hasPipeTobacco: shop.hasPipeTobacco ?? false,
                hasMemberAccess: shop.hasMemberAccess ?? false,
                hasHooka: shop.hasHooka ?? false,
                hasEvents: shop.hasEvents ?? false,
                hasLiquorLicense: shop.hasLiquorLicense ?? false,
                canBringInLiquor: shop.canBringInLiquor ?? false,
                hasInternetAccess: shop.hasInternetAccess ?? false,
                hasCoffeeMaker: shop.hasCoffeeMaker ?? false,
                hasIceMaker: shop.hasIceMaker ?? false,
                hasBigTV: shop.hasBigTV ?? false,
                sellsAccessories: shop.sellsAccessories,
                latitude: "latitude" in shop ? shop.latitude ?? null : null,
                longitude: "longitude" in shop ? shop.longitude ?? null : null,
                isFeatured: "isFeatured" in shop ? shop.isFeatured ?? false : false,
                isSponsored: "isSponsored" in shop ? shop.isSponsored ?? false : false,
            },
        });
    }
}

main()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (error) => {
        console.error(error);
        await prisma.$disconnect();
        process.exit(1);
    });