import type { Shop } from "./types";

export const alabamaShops: Shop[] = [
    {
        id: "1",
        slug: "the-humidor-room-cigar-and-scotch-bar",
        name: "The Humidor Room cigar & Scotch Bar",
        city: "Birmingham",
        stateabb: "AL",
        state: "Alabama",
        zip: "35233",
        address: "2115 7th Ave S, Birmingham, AL 35233",
        phone: "(205) 995-4481",
        website: "https://humidorroom.com",
        hours: {
            mon: "10AM - Midnight",
            tue: "10AM - Midnight",
            wed: "10AM - Midnight",
            thu: "10AM - Midnight",
            fri: "10AM- 2AM",
            sat: "10AM- 2AM",
            sun: "2PM- 10PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: true,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The Humidor Room offers a Full Bar to accompany a Wide Variety of Fine Cigars and Tobacco Products from around the World. Specialty Cocktails and a Fine Selection of Wines are also offered by the Glass or Bottle.",
        latitude: 33.506719,
        longitude: -86.797695,
        image: "/images/humidorAL/1.jpg",
        gallery: [
            "/images/humidorAL/1.jpg",
            "/images/humidorAL/2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]