import type { Shop } from "./types";

export const arkansasShops: Shop[] = [
    {
        id: "1",
        slug: "cigar-republic",
        name: "Cigar Republic",
        city: "Little Rock",
        stateabb: "AR",
        state: "Arkansas",
        zip: "72227",
        address: "1315 Breckenridge Dr, Little Rock, AR 72227",
        phone: "(501) 615-8040",
        website: "https://www.cigarrepublic.com/",
        hours: {
            mon: "1PM - 11PM",
            tue: "1PM - 11PM",
            wed: "1PM - 11PM",
            thu: "1PM - Midnight",
            fri: "1PM - Midnight",
            sat: "11AM - Midnight",
            sun: "3PM - 10PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Arkansas' Largest Walk-In Humidor",
        latitude: 34.766697,
        longitude: -92.386303,
        image: "/images/republicAR/img1.jpg",
        gallery: [
            "/images/republicAR/img1.jpg",
            "/images/republicAR/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]