import type { Shop } from "./types";

export const coloradoShops: Shop[] = [
    {
        id: "1",
        slug: "smoking-cave-cigar-lounge",
        name: "Smoking Cave Cigar Lounge",
        city: "Corrales",
        stateabb: "CO",
        state: "Colorado",
        zip: "80126",
        address: "5435 Boatworks Dr, Highlands Ranch, CO 80126",
        phone: "(303) 713-0022",
        website: "https://smokingcave.com/",
        hours: {
            mon: "8AM - 10PM",
            tue: "8AM - 10PM",
            wed: "8AM - 10PM",
            thu: "8AM - 10PM",
            fri: "8AM - 10PM",
            sat: "8AM - 10PM",
            sun: "10AM - 6PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: false,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Our full craft bar in Phoenix (Ahwatukee) is designed for the discerning spirits enthusiast. From world-renowned whiskies + bourbons, to boutique and small batch releases - we've curated an amazing selection for you to enjoy.",
        latitude: 39.565626,
        longitude: -104.924832,
        image: "/images/smokingcaveco/img1.jpg",
        gallery: [
            "/images/smokingcaveco/img1.jpg",
            "/images/smokingcaveco/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    ]