import type { Shop } from "./types";

export const washingtondcShops: Shop[] = [
    {
        id: "1",
        slug: "wperiod-curtis-draper-tobacoonist",
        name: "W. Curtis Draper Tobacconist",
        city: "Anchorage",
        stateabb: "DC",
        state: "Washington DC",
        zip: "2005",
        address: "699 15th St NW, Washington, DC 20005",
        phone: "(202) 638-2555",
        website: "http://www.wcurtisdraper.com",
        hours: {
            mon: "10 AM-5 PM",
            tue: "10 AM-5 PM",
            wed: "10 AM-5 PM",
            thu: "10 AM-5 PM",
            fri: "10 AM-5 PM",
            sat: "Closed",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 38.8985,
        longitude: -77.033368,
        image: "/images/drapersDC/img1.jpg",
        gallery: [
            "/images/drapersDC/img1.jpg",
            "/images/drapersDC/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]