import type { Shop } from "./types";

export const delawareShops: Shop[] = [
    {
        id: "1",
        slug: "the-sikar-cigar-lounge",
        name: "The Sikar Cigar Lounge",
        city: "Wilmington",
        stateabb: "DE",
        state: "Delaware",
        zip: "19806",
        address: "1624 Delaware Ave, Wilmington, DE 19806",
        phone: "(302) 655-2250",
        website: "https://www.facebook.com › SikarLounge",
        hours: {
            mon: "5PM - 12AM",
            tue: "5PM - 12AM",
            wed: "5PM - 12AM",
            thu: "5PM - 12AM",
            fri: "2PM - 1 AM",
            sat: "2PM - 1 AM",
            sun: "5PM - 12AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Delaware's premiere cigar lounge located in the heart of Trolley Square!.",
        latitude: 39.757679,
        longitude: -75.562577,
        image: "/images/sikarde/img1.jpg",
        gallery: [
            "/images/sikarde/img1.jpg",
            "/images/sikarde/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]