import type { Shop } from "./types";

export const floridaShops: Shop[] = [
    {
        id: "1",
        slug: "bonita-smoke-shop-and-cigar-lounge",
        name: "Bonita Smoke Shop & Cigar Lounge",
        city: "Estero",
        stateabb: "FL",
        state: "Florida",
        zip: "33928",
        address: "23050 Via Villagio Pkwy, Estero, FL 33928",
        phone: "(239) 495-9296",
        website: "http://www.bonitasmokeshop.com",
        hours: {
            mon: "9AM - 9PM",
            tue: "9AM - 9PM",
            wed: "9AM - 9PM",
            thu: "9AM - 9PM",
            fri: "9AM - 9PM",
            sat: "9AM - 9PM", 
            sun: "10AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Bonita Beach, FL – Bonita Smoke Shop, a beloved local institution for over 30 years, is thrilled to announce its relocation and expansion to Coconut Point Shopping Center will be operating under Bonita Smoke Shop & Cigar Lounge.  The new location will feature a significantly expanded retail space boasting over 6,600 square feet dedicated to a world-class selection of cigars.",
        latitude: 26.40693,
        longitude: -81.809575,
        image: "/images/bonita/front.jpg",
        gallery: [
            "/images/bonita/front.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
]