import type { Shop } from "./types";

export const hawaiiShops: Shop[] = [
    {
        id: "1",
        slug: "tobaccos-of-hawaii",
        name: "Tobaccos of Hawaii",
        city: "Honolulu",
        stateabb: "HI",
        state: "Hawaii",
        zip: "96826",
        address: "2043 S Beretania St, Honolulu, HI 96826",
        phone: "(808) 942-7855",
        website: "http://www.tobaccosofhawaii.com",
        hours: {
            mon: "9am - 8PM",
            tue: "9am - 8PM",
            wed: "9am - 8PM",
            thu: "9am - 8PM",
            fri: "9am - 8PM",
            sat: "9am - 8PM",
            sun: "9am - 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "At Tobaccos of Hawaii, we believe that Hawaii tobacco lovers deserve the very best quality and service from their smoke shop. We are tobacco enthusiasts just like you, and our staff is knowledgeable and courteous, friendly, and always professional.",
        latitude: 21.295983,
        longitude: -157.828801,
        image: "/images/tobaccosofhawaii/image1.jpg",
        gallery: [
            "/images/tobaccosofhawaii/image1.jpg",
            "/images/tobaccosofhawaii/image2.jpg",
            "/images/tobaccosofhawaii/image3.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]