import type { Shop } from "./types";

export const indianaShops: Shop[] = [
    {
        id: "1",
        slug: "burn-by-rocky-patel-indianapolis",
        name: "Burn by Rocky Patel Indianapolis",
        city: "Indianapolis",
        stateabb: "IN",
        state: "Indiana",
        zip: "46225",
        address: "110 S Meridian St, Indianapolis, IN 46225",
        phone: "(317) 602-2260",
        website: "https://www.burnbyrockypatel.com › indianapolis",
        hours: {
            mon: "4PM - 2AM",
            tue: "4PM - 2AM",
            wed: "4PM - 2AM",
            thu: "4PM - 2AM",
            fri: "4PM - 2AM",
            sat: "4PM - 2AM",
            sun: "4PM - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Welcome to BURN Indianapolis, where luxury and sophistication converge to offer an unparalleled experience for aficionados of premium cigars, fine spirits, craft cocktails and live entertainment.",
        latitude: 61.217821,
        longitude: -149.874144,
        image: "/images/rockyIN/img1.jpg",
        gallery: [
            "/images/rockyIN/img1.jpg",
            "/images/rockyIN/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]