import type { Shop } from "./types";

export const kansasShops: Shop[] = [
    {
        id: "1",
        slug: "the-humidor-cocktail-lounge",
        name: "The Humidor Cocktail Lounge",
        city: "Wichita",
        stateabb: "KS",
        state: "Kansas",
        zip: "67205",
        address: "8558 W 21st St N, Wichita, KS 67205",
        phone: "(907) 274-7473",
        website: "http://www.avenuecigars.com",
        hours: {
            mon: "1PM- 11PM",
            tue: "1PM-12:30AM",
            wed: "1PM-12:30AM",
            thu: "1PM-12:30AM",
            fri: "Noon- 2AM",
            sat: "Noon- 2AM",
            sun: "Noon- 11PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Humidor Cocktail Lounge, the largest premium cigar and cocktail lounge in Wichita, Kansas, featuring live music every Friday and Saturday, beginning at 8 pm.",
        latitude: 37.724312,
        longitude: -97.441916,
        image: "/images/humidorKS/img1.jpg",
        gallery: [
            "/images/humidorKS/img1.jpg",
            "/images/humidorKS/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]