import type { Shop } from "./types";

export const louisianaShops: Shop[] = [
    {
        id: "1",
        slug: "cuban-creations-cigar-bar",
        name: "Cuban Creations Cigar Bar",
        city: "New Orleans",
        stateabb: "LA",
        state: "Louisiana",
        zip: "70130",
        address: "533 Toulouse St, New Orleans, LA 70130",
        phone: "(504) 372-4838",
        website: "http://www.cigarbarnola.com",
        hours: {
            mon: "11AM - 2AM",
            tue: "11AM - 2AM",
            wed: "11AM - 2AM",
            thu: "11AM - 2AM",
            fri: "11AM - 2AM",
            sat: "11AM - 2AM",
            sun: "11AM - 2AM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Welcome to Cuban Creations the best bar in New Orleans, where our delectable drinks and large variety of the finest premium and handmade sticks await you",
        latitude: 29.956509,
        longitude: -90.064252,
        image: "/images/cubanla/img1.jpeg",
        gallery: [
            "/images/cubanla/img1.jpeg",
            "/images/cubanla/img2.jpeg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]