import type { Shop } from "./types";

export const michiganShops: Shop[] = [
    {
        id: "1",
        slug: "la-casa-cigars-and-lounge",
        name: "La Casa Cigars and Lounge",
        city: "Detroit",
        stateabb: "MI",
        state: "Michigan",
        zip: "48266",
        address: "1502 Randolph St, Detroit, MI 48226",
        phone: "(313) 285-8332",
        website: "http://www.lacasacigars.com",
        hours: {
            mon: "10AM - Midnight",
            tue: "10AM - Midnight",
            wed: "10AM - Midnight",
            thu: "10AM - 1AM",
            fri: "10AM - 2AM",
            sat: "10AM - 2AM",
            sun: "Noon - 12:30AM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "WELCOME TO Cigar Sanctuary",
        latitude: 42.33664,
        longitude: -83.046024,
        image: "/images/lacasaMI/img1.jpg",
        gallery: [
            "/images/lacasaMI/img1.jpg",
            "/images/lacasaMI/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]