import type { Shop } from "./types";

export const mississippiShops: Shop[] = [
    {
        id: "1",
        slug: "signature-bar-and-cigar-lounge",
        name: "Signature Bar & Cigar Lounge",
        city: "D'Iberville",
        stateabb: "MS",
        state: "Mississippi",
        zip: "39540",
        address: "3516 Sangani Blvd, D'Iberville, MS 39540",
        phone: "(228) 967-7625",
        website: "https://signature-bar-cigar-lounge.ueniweb.com",
        hours: {
            mon: "Noon- 11PM",
            tue: "Noon- 11PM",
            wed: "Noon- Midnight",
            thu: "Noon- 3AM",
            fri: "Noon- 3AM",
            sat: "Noon- 3AM",
            sun: "Noon- 10PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 30.459119,
        longitude: -88.892095,
        image: "/images/signatureMS/img1.jpg",
        gallery: [
            "/images/signatureMS/img1.jpg", 
            "/images/signatureMS/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]