import type { Shop } from "./types";

export const montanaShops: Shop[] = [
    {
        id: "1",
        slug: "omerta-cigar-lounge",
        name: "Omerta Cigar Lounge",
        city: "Great Falls",
        stateabb: "MT",
        state: "Montana",
        zip: "59401",
        address: "3 4th Street North, Great Falls, Montana 59401",
        phone: "admin@omertacigarlounge.com",
        website: "https://omertacigarlounge.com/",
        hours: {
            mon: "10AM - 830PM",
            tue: "10AM - 830PM",
            wed: "10AM - 830PM",
            thu: "10AM - 830PM",
            fri: "10AM - 10PM",
            sat: "10AM - 10PM",
            sun: "10AM - 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Welcome to Omerta Cigar Lounge Great Falls, MT",
        latitude: 47.505713,
        longitude: -111.300533,
        image: "/images/omertaMT/img1.jpg",
        gallery: [
            "/images/omertaMT/img1.jpg",
            "/images/omertaMT/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 32,
    },
    ]