import type { Shop } from "./types";

export const newjerseyShops: Shop[] = [
    {
        id: "1",
        slug: "10-north-lounge",
        name: "10 North Lounge",
        city: "Atlantic City",
        stateabb: "NJ",
        state: "New Jersey",
        zip: "08401",
        address: "2831 Boardwalk, Atlantic City, NJ 08401",
        phone: "(800) 843-8767",
        website: "https://www.caesars.com › tropicana-ac › things-to-do › nightlife",
        hours: {
            mon: "24 hours",
            tue: "24 hours",
            wed: "24 hours",
            thu: "24 hours",
            fri: "24 hours",
            sat: "24 hours",
            sun: "24 hours",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: true,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Sophisticated and upscale, sip top-shelf libations and stay close to the action with bar-top gaming, or get cozy around our statement double-sided fireplace.",
        latitude: 39.352361,
        longitude: -74.445377,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    ]