import type { Shop } from "./types";

export const newmexicoShops: Shop[] = [
    {
        id: "1",
        slug: "padres-cigars",
        name: "Padres Cigars",
        city: "Corrales",
        stateabb: "NM",
        state: "New Mexico",
        zip: "87048",
        address: "4605 Corrales Rd. Corrales New Mexico 87048",
        phone: "",
        website: "https://www.padrescigars.com/home",
        hours: {
            mon: "Closed",
            tue: "Closed",
            wed: "Closed",
            thu: "Closed",
            fri: "11AM - 8PM",
            sat: "11AM - 8PM",
            sun: "11AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: false,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Our full craft bar in Phoenix (Ahwatukee) is designed for the discerning spirits enthusiast. From world-renowned whiskies + bourbons, to boutique and small batch releases - we've curated an amazing selection for you to enjoy.",
        latitude: 35.226303,
        longitude: -106.614444,
        image: "/images/padresnm/img1.jpg",
        gallery: [
            "/images/padresnm/img1.jpg",
            "/images/padresnm/img2.jpg",

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    ]