import type { Shop } from "./types";

export const northdakotaShops: Shop[] = [
    {
        id: "1",
        slug: "big-stick-cigar-lounge",
        name: "Big Stick Cigar Lounge",
        city: "Mandan",
        stateabb: "ND",
        state: "North Dakota",
        zip: "58554",
        address: "104 2nd Ave NW, Mandan, ND 58554",
        phone: "(701) 751-1029",
        website: "http://www.bigstickcigarsnd.com",
        hours: {
            mon: "Noon - 1AM",
            tue: "Noon - 1AM",
            wed: "Noon - 1AM",
            thu: "Noon - 1AM",
            fri: "Noon - 1AM",
            sat: "Noon - 1AM",
            sun: "Noon - 8PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Located in legendary downtown Mandan.  Big Stick Cigar Lounge is North Dakota's coolest vintage cigar lounge.",
        latitude: 46.826512,
        longitude: -100.892579,
        image: "/images/BigStickND/img1.avif",
        gallery: [
            "/images/BigStickND/img1.avif",
            "/images/BigStickND/img2.avif",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 32,
    },
    ]