import type { Shop } from "./types";

export const oklahomaShops: Shop[] = [
    {
        id: "1",
        slug: "ash-cigar-lounge",
        name: "ASH Cigar Lounge",
        city: "Oklahoma City",
        stateabb: "OK",
        state: "Oklahoma",
        zip: "73102",
        address: "712 N Broadway Ave, Oklahoma City, OK 73102",
        phone: "(405) 673-7452",
        website: "http://www.ashcigarloungeokc.com",
        hours: {
            mon: "Noon - 10PM",
            tue: "Noon - 10PM",
            wed: "Noon - Midnight",
            thu: "Noon - Midnight",
            fri: "Noon - Midnight",
            sat: "Noon - Midnight",
            sun: "Closed"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Enjoy a wide selection of cigars from our humidor or bring your own.",
        latitude: 35.474585,
        longitude: -97.513847,
        image: "/images/ashOK/img1.jpg",
        gallery: [
            "/images/ashOK/img1.jpg",
            "/images/ashOK/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]