import type { Shop } from "./types";

export const oregonShops: Shop[] = [
    {
        id: "1",
        slug: "cigars-on-seventh",
        name: "Cigars on 7th",
        city: "Lacey",
        stateabb: "OR",
        state: "Oregon",
        zip: "97401",
        address: "679 Lincoln St, Eugene, OR 97401",
        phone: "(541) 654-5004",
        website: "https://cigarson7th.com",
        hours: {
            mon: "10AM - 7PM",
            tue: "10AM - 7PM",
            wed: "10AM - 7PM",
            thu: "10AM - 7PM",
            fri: "10AM - 7PM",
            sat: "10AM - 7PM",
            sun: "10AM - 3PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "We Believe that wanting the best should never get in the way of wanting to relax..",
        latitude: 44.052408,
        longitude: -123.097094,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]