import type { Shop } from "./types";

export const pennsylvaniaShops: Shop[] = [
    {
        id: "1",
        slug: "ashton-cigar-bar",
        name: "Ashton Cigar Bar",
        city: "Philadelphia",
        stateabb: "PA",
        state: "Pennsylvania",
        zip: "19102",
        address: "1522 Walnut St, Philadelphia, PA 19102",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: {
            mon: "4pm - 11PM",
            tue: "4pm - 11PM",
            wed: "4pm - 11PM",
            thu: "4pm - 11PM", 
            fri: "4pm - 11PM", 
            sat: "4pm - 11PM",
            sun: "4pm - 11PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: true,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: true,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Modern, upscale cigar lounge and cocktail bar with an extensive menu of whiskey, cocktails, spirits, and cigars. Located above Holt’s Cigar Shop in downtown Philadelphia. You can still purchase cigars from the Holt's Cigar Shop online and in store.",
        latitude: 39.949464,
        longitude: -75.167106,
        image: "/images/ashtonpa/ashtonpa1.jpg",
        gallery: [
            "/images/ashtonpa/ashtonpa1.jpg",
            "/images/ashtonpa/logo.svg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.1,
        reviewCount: 1123,
    },
    ]