import type { Shop } from "./types";

export const rhodeislandShops: Shop[] = [
    {
        id: "1",
        slug: "white-ash-cigar-lounge",
        name: "White Ash Cigar Lounge",
        city: "Pawtucket",
        stateabb: "RI",
        state: "Rhode Island",
        zip: "02861",
        address: "413 Central Ave, Pawtucket, RI 02861",
        phone: "(401) 726-1715",
        website: "https://whiteashcigarlounge.com",
        hours: {
            mon: "Noon - Midnight",
            tue: "11AM - Midnight",
            wed: "11AM - Midnight",
            thu: "11AM - 1 AM",
            fri: "11AM - 1 AM",
            sat: "11AM - 1 AM", 
            sun: "Noon - Midnight",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Nestled in the heart of Pawtucket, our sophisticated cigar lounge strikes the perfect balance between refined elegance and welcoming comfort..",
        latitude: 41.884641,
        longitude: -71.365507,
        image: "/images/whiteashRI/img1.png",
        gallery: [
            "/images/whiteashRI/img1.png",
            "/images/whiteashRI/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]