export type Shop = {
    id: string;
    slug: string;
    name: string;
    city: string;
    stateabb: string;
    state: string;
    zip: string;
    address: string;
    phone: string;
    website?: string;
    hours?: string;
    hasLounge: boolean;
    hasHumidor: boolean;
    hasPadrons: boolean;
    hasFuentes: boolean;
    hasDavidoffs: boolean;
    hasOpusX: boolean;
    hasAcid: boolean;
    hasPerdomos: boolean;
    hasLFDs: boolean;
    hasOlivas: boolean;
    hasAtabeys: boolean;
    hasHouseCigars: boolean;
    hasAltadis: boolean;
    hasGeneralCigar: boolean;
    hasRareOpusX: boolean;
    hasMemberLockers: boolean;
    sellsFood: boolean;
    hasPipeTobacco: boolean;
    hasMemberAccess: boolean;
    hasEvents: boolean;
    hasHooka: boolean;
    hasLiquorLicense: boolean;
    canBringInLiquor: boolean;
    hasInternetAccess: boolean;
    hasCoffeeMaker: boolean;
    hasIceMaker: boolean;
    hasBigTV: boolean;
    sellsAccessories: boolean;
    description: string;
    latitude: number;
    longitude: number;
    image?: string;
    gallery?: string[];
    isFeatured?: boolean;
    isSponsored?: boolean;
    rating?: number;
    reviewCount?: number;

};

export const shops: Shop[] = [
    {
        id: "1",
        slug: "davidus-cigars-annapolis",
        name: "Davidus Cigars- Annapolis",
        city: "Annapolis",
        stateabb: "MD",
        state: "Maryland",
        zip: "21401",
        address: "2134 Generals Hwy, Annapolis, MD 21401",
        phone: "(410) 573-1212",
        website: "http://www.davidus.com",
        hours: "M-TH 10 AM-9 PM, Fri and Sat 10AM-11PM, SUN 11 AM-7PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: true,
        hasIceMaker: true,
        hasBigTV: true,
        sellsAccessories: false,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 38.9784,
        longitude: -76.5434,
        image: "/images/DavidusAnnapolis/front.jpg",
        gallery: [
            "/images/DavidusAnnapolis/cl-annapolis-3.jpg",
            "/images/DavidusAnnapolis/Davidus_Logo.png",
            "/images/DavidusAnnapolis/front.jpg",
            "/images/DavidusAnnapolis/cl-annapolis-11.jpg",
            "/images/DavidusAnnapolis/JohnS.jpg"
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 2.5,
        reviewCount: 131,
        },
    {
        id: "2",
        slug: "davidus-cigars-baltimore-federal-hill",
        name: "Davidus Cigars- Baltimore (Federal Hill)",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21230",
        address: "1011 Light St, Baltimore, MD 21230",
        phone: "(443) 449-5871",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.27794,
        longitude: -76.612265,
        image: "/images/fedhill/baltimore_light_st._8.jpg",
        gallery: [
            "/images/fedhill/baltimore_light_st._8.jpg",
            "/images/fedhill/wedsite-managerBAL-LS.jpeg",
            "/images/fedhill/baltimore_light_st._6.jpg",
            "/images/fedhill/baltimore_light_st._7.jpg"
            
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
        },
    {
        id: "3",
        slug: "davidus-cigars-ellicott-city",
        name: "Davidus Cigars- Ellicott City",
        city: "Ellicott City",
        stateabb: "MD",
        state: "Maryland",
        zip: "21042",
        address: "9180 Baltimore National Pike, Ellicott City, MD 21042",
        phone: "(410) 480-4810",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.278012,
        longitude: -76.829263,
        image: "/images/DavidusEllicott/Ellicottfront.jpg",
        gallery: [
            "/images/DavidusEllicott/Ellicott_Citymgr.jpg",
            "/images/DavidusEllicott/cl-ellicottcity-8.jpg",
            "/images/DavidusEllicott/Ellicottfront.jpg",
            "/images/DavidusEllicott/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 1.9,
        reviewCount: 15
        },
    {
        id: "4",
        slug: "davidus-cigars-ashton",
        name: "Davidus Cigars- Ashton",
        city: "Ashton",
        stateabb: "MD",
        state: "Maryland",
        zip: "20861",
        address: "25 Olney Sandy Spring Rd, Ashton, MD 20861",
        phone: "(301) 260-0788",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.149909,
        longitude: -77.013536,
        image: "/images/Davidus-Ashton/ashtonmdlounge.jpg",
        gallery: [
            "/images/Davidus-Ashton/ashtonmdlounge.jpg",
            "/images/Davidus-Ashton/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.4,
        reviewCount: 24,
        },
    {
        id: "5",
        slug: "broadleaf-tobacco",
        name: "Broadleaf Tobacco",
        city: "Severna Park",
        stateabb: "MD",
        state: "Maryland",
        zip: "21146",
        address: "487 Ritchie Hwy, Severna Park, MD 21146",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: "M-TH 10 AM-9 PM, Fri and Sat 10AM-11PM, SUN 11 AM-7PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: true,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Severna Park based Premium cigar shop with a comfortable lounge and curated humidor.",
        latitude: 39.083265,
        longitude: -76.549876,
        image: "/images/BLT/bltlounge1.jpg",
        gallery: [
            "/images/BLT/BLTlogo.png",
            "/images/BLT/BLTcrowd.jpg",
            "/images/BLT/bltlounge1.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 122,
    },
    {
        id: "6",
        slug: "aphelion-cigar-lounge",
        name: "Aphelion Cigar Lounge",
        city: "Gambrills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21054",
        address: "2510 Conway Rd, Gambrills, MD 21054",
        phone: "(410) 721-1700",
        website: "http://aphelioncigarlounge.com",
        hours: "Friday 10 AM - 2 AM, Saturday	10 AM - 1 AM, Sunday 10 AM - midnight, Easter, hours may vary, M-W 10 AM - midnight, Thursday 10AM-1 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasCoffeeMaker: false,
        hasIceMaker: true,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Aphelion is the FIRST Black Owned cigar lounge and full bar to open in the state of Maryland. The founder(s) and owners James Price and Robert Monroe are true pioneers with nearly 15 years in this amazing industry.",
        latitude: 39.021416,
        longitude: -76.697973,
        image: "/images/aphelion/img1.jpg",
        gallery: [
            "/images/aphelion/img1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.1,
        reviewCount: 44,
        },
    {
        id: "7",
        slug: "ashton-cigar-bar",
        name: "Ashton Cigar Bar",
        city: "Philadelphia",
        stateabb: "PA",
        state: "Pennsylvania",
        zip: "19102",
        address: "1522 Walnut St, Philadelphia, PA 19102",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: "M-TH 4 PM-11 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Modern, upscale cigar lounge and cocktail bar with an extensive menu of whiskey, cocktails, spirits, and cigars. Located above Holt’s Cigar Shop in downtown Philadelphia. You can still purchase cigars from the Holt's Cigar Shop online and in store.",
        latitude: 39.949464,
        longitude: -75.167106,
        image: "/images/ashtonpa/ashtonpa1.jpg",
        gallery: [
            "/images/ashtonpa/ashtonpa1.jpg",
            "/images/ashtonpa/logo.svg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.1,
        reviewCount: 1123,
        },
    {
        id: "8",
        slug: "casa-de-montecristo-cigar-lounge",
        name: "Casa de Montecristo Cigar Lounge",
        city: "New York City",
        stateabb: "NY",
        state: "New York",
        zip: "10022",
        address: "1016 2nd Ave, New York, NY 10022",
        phone: "(212) 750-0809",
        website: "",
        hours: "M-SUN 11AM-11 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Casa De Montecristo New York – one of the finest cigar lounges in NYC. With its superb stogie collection, you’re guaranteed to find a cigar brand, type and size that meets your needs. Don’t worry if you’re a complete novice when it comes to cigars. Simply have a chat with a member of our onsite friendly and educated team.",
        latitude: 40.757073,
        longitude: -73.966604,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "9",
        slug: "Windy-city-cigar-lounge",
        name: "Windy City Cigar Lounge",
        city: "Chicago",
        stateabb: "IL",
        state: "Illinois",
        zip: "60653",
        address: "4310 S Prairie Ave, Chicago, IL 60653",
        phone: "(773) 855-2143",
        website: "",
        hours: "Friday 5 PM - 1 AM, Saturday 5 PM - 1 AM, Sunday 11 AM - 11 PM, Easter, hours may vary, Monday & Tuesday Closed, Wednesday 5 PM - midnight, Thursday 5 PM - midnight",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "A cigar lounge for the sophisticated cigar aficionado",
        latitude: 41.816167,
        longitude: -87.620028,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "10",
        slug: "magoo-cigar-lounge",
        name: "Magoo's Cigar Lounge",
        city: "Norfolk",
        stateabb: "VA",
        state: "Virginia",
        zip: "60653",
        address: "246 E Main St, Norfolk, VA 23510",
        phone: "(757) 937-5047",
        website: "",
        hours: "Friday & Saturday 11 AM - 10 PM, Sunday	Noon - 6 PM, Easter, hours may vary, M-TH 11 AM - 8:30 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Magoo's Cigar Lounge is a Cigar shop located in Norfolk.",
        latitude: 42.37747,
        longitude: -71.06699,
        image: "/images/magoos/magooslogo.jpg",
        gallery: [
            "/images/magoos/magooslogo.jpg",
            "/images/magoos/lounge1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "11",
        slug: "boston-cigar-lounge",
        name: "Boston Cigar Lounge",
        city: "Boston",
        stateabb: "MA",
        state: "Massachussetts",
        zip: "02129",
        address: "73 Main St, Boston, MA 02129",
        phone: "(617) 242-6010",
        website: "https://bostoncigarclub.com",
        hours: "Monday-Sunday 3 PM- 1 AM, Easter, hours may vary",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Discover an unparalleled escape at Boston Cigar Club & Shop, a sophisticated destination where the worlds of premium cigars, exquisite spirits, and gourmet cuisine unite. Explore our extensive selection of fine tobacco in the dedicated cigar shop, boasting its own humidor. Then, unwind in our refined lounge, featuring a …",
        latitude: 42.373532,
        longitude: -71.061562,
        image: "/images/bostoncigar/bostonlounge1.jpg",
        gallery: [
            "/images/bostoncigar/bostonlounge1.jpg",
            "/images/bostoncigar/lounge2.jpg", 
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "12",
        slug: "prime-cigar-bar",
        name: "Prime Cigar",
        city: "Atlanta",
        stateabb: "GA",
        state: "Georgia",
        zip: "30309",
        address: "1035 Peachtree St NE, Atlanta, GA 30309",
        phone: "(404) 941-7130",
        website: "https://primecigaratl.com/",
        hours: "Monday-Sunday 3 PM- 1 AM, Easter, hours may vary",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Welcome to Atlanta’s Most Premier Cigar Lounge. Let’s dine, drink, smoke.  Enjoy from a selection of our handcrafted cocktails or one of your favorite premium drinks. Our bartender will be sure to have you coming back all night long.",
        latitude: 33.782868,
        longitude: -84.383753,
        image: "/images/atlantaprime/InteriorShot-scaled.jpg",
        gallery: [
            "/images/atlantaprime/InteriorShot-scaled.jpg",
                    ],
        isSponsored: true,
        rating: 3.1,
        reviewCount: 54,
    },
    {
        id: "13",
        slug: "titan-cigar",
        name: "Titan Cigar",
        city: "Gambrills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21054",
        address: "2634 Chapel Lake Dr, Gambrills, MD 21054",
        phone: "410-721-0100",
        website: "https://titancigar.com/",
        hours: "Monday-Sunday 3 PM- 1 AM, Easter, hours may vary",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: false,
        description: "Visit us in The Village at Waugh Chapel, Gambrills, Maryland. We offer a wide variety of premium and hard-to-find cigars, as well as accessories like humidors, lighters, and cutters. Our friendly and knowledgeable staff are here to assist you with your selections.",
        latitude: 39.039779,
        longitude: -76.680763,
        image: "/images/titan/titanfront.jpg",
        gallery: [
            "/images/titan/titanfront.jpg"
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.1,
        reviewCount: 94,
    },
    {
        id: "14",
        slug: "davidus-cigars-towson",
        name: "Davidus Cigars- Towson",
        city: "Towson",
        stateabb: "MD",
        state: "Maryland",
        zip: "21204",
        address: "25 Allegheny Ave, Towson, MD 21204",
        phone: "(410) 616-9906",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.401555,
        longitude: -76.604001,
        image: "/images/towson/cl-towson-1.jpg",
        gallery: [
            "/images/towson/cl-towson-1.jpg",
            "/images/towson/towsonmgr.jpg",
            "/images/towson/cl-towson-10.jpg",
            "/images/towson/cl-towson-4.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "15",
        slug: "davidus-cigars-westminster",
        name: "Davidus Cigars- Westminster",
        city: "Westminster",
        stateabb: "MD",
        state: "Maryland",
        zip: "21157",
        address: "23 East Main Street, Westminster, MD 21157",
        phone: "(410) 876-4786",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        sellsFood: false,
        hasRareOpusX: false,
        hasMemberLockers: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.574814,
        longitude: -76.995304,
        image: "/images/westminster/cl-westminster-1.jpg",
        gallery: [
            "/images/westminster/wedsite-managerWES.jpg",
            "/images/westminster/cl-westminster-8.jpg",
            "/images/westminster/cl-westminster-4.jpeg",
            "/images/westminster/cl-westminster-1.jpg"
            
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "16",
        slug: "davidus-cigars-frederick",
        name: "Davidus Cigars- Frederick",
        city: "Frederick",
        stateabb: "MD",
        state: "Maryland",
        zip: "21071",
        address: "​529 West South Street, Frederick, MD 21157",
        phone: "301-662-6606",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.4127,
        longitude: -77.42426,
        image: "/images/frederick/cl-frederick-7.jpg",
        gallery: [
            "/images/frederick/Frederick-manager.jpg",
            "/images/frederick/cl-frederick-3.jpg",
            "/images/frederick/cl-frederick-1.jpg",
            "/images/frederick/cl-frederick-7.jpg",
                   ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "17",
        slug: "davidus-cigars-urbana",
        name: "Davidus Cigars- Urbana",
        city: "Urbana",
        stateabb: "MD",
        state: "Maryland",
        zip: "21704",
        address: "8925 Fingerboard Road, Urbana, MD 21704",
        phone: "301-874-1100",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.325074,
        longitude: -77.348089,
        image: "/images/urbana/cl-urbanasouthfrederick-1.jpg",
        gallery: [
            "/images/urbana/cl-urbanasouthfrederick-6.jpg",
            "/images/urbana/wedsite-managerURB.jpg",
            "/images/urbana/cl-urbanasouthfrederick-9.jpg",
            "/images/urbana/cl-urbanasouthfrederick-1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "18",
        slug: "davidus-cigars-shady-grove",
        name: "Davidus Cigars- Shady Grove",
        city: "Shady Grove",
        stateabb: "MD",
        state: "Maryland",
        zip: "20877",
        address: "15922 Shady Grove Road, Gaithersburg, MD 20877",
        phone: "301-963-8400",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.118357,
        longitude: -77.183874,
        image: "/images/shady/cl-shadygroveroad-14.jpg",
        gallery: [
            "/images/shady/cl-shadygroveroad-manager-bc-jen.jpg",
            "/images/shady/cl-shadygroveroad-4.jpg",
            "/images/shady/cl-shadygroveroad-14.jpg",
            "/images/shady/cl-shadygroveroad-7.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "19",
        slug: "davidus-cigars-owings-mills",
        name: "Davidus Cigars- Owings Mills",
        city: "Owings Mills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21117",
        address: "10810 Reisterstown Road, Owings Mills, MD 21117",
        phone: "443-449-5871",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasFuentes: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.118357,
        longitude: -77.183894,
        image: "/images/owings/cl-owingsmills-2.jpg",
        gallery: [
            "/images/owings/Owings_Mills-_Reisterstown.jpg",
            "/images/owings/img-2614_orig.jpg",
            "/images/owings/front",
            "/images/owings/cl-owingsmills-2.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.7,
        reviewCount: 70,
    },
    {
        id: "20",
        slug: "davidus-cigars-baltimore-little-italy",
        name: "Davidus Cigars- Baltimore (Little Italy)",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21231",
        address: "1300 Bank Street (Central Ave), Baltimore, MD 21231",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.286622,
        longitude: -76.598793,
        image: "/images/Daviduslittleitaly/image_10.jpg",
        gallery: [
            "/images/Daviduslittleitaly/image_6.jpg.jpg",
            "/images/Daviduslittleitaly/wedsite-manageritaly.jpeg",
            "/images/Daviduslittleitaly/image_10.jpg",
            "/images/Daviduslittleitaly/image_13.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "21",
        slug: "davidus-cigars-rockville",
        name: "Davidus Cigars- Rockville",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "20852",
        address: "11632 Rockville Pike, Rockville, MD 20852",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        latitude: 39.048158,
        longitude: -77.114255,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/rockville/cl-rockvillepike-1.jpg",
        gallery: [
            "/images/rocvkille/wedsite-managerROC_copy.jpg",
            "/images/rockville/cl-rockvillepike-1.jpg",
            "/images/rockville/cl-rockvillepike-4.jpg",
            "/images/rockville/cl-rockvillepike-7.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "22",
        slug: "davidus-cigars-eldersburg",
        name: "Davidus Cigars- Eldersburg",
        city: "Eldersburg",
        stateabb: "MD",
        state: "Maryland",
        zip: "21784",
        address: "11716 Liberty Road, Eldersburg, MD 21784",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        latitude: 39.396577,
        longitude: -76.922275,
        image: "/images/eldersburg/cl-eldersburg-7.jpg",
        gallery: [
            "/images/eldersburg/cl-eldersburg-7.jpg",
            "/images/eldersburg/eldersburg-manager.jpg",
            "/images/eldersburg/front.jpg",
            "/images/eldersburg/cl-eldersburg-5.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "23",
        slug: "bonita-smoke-shop-and-cigar-lounge",
        name: "Bonita Smoke Shop & Cigar Lounge",
        city: "Estero",
        stateabb: "FL",
        state: "Florida",
        zip: "33928",
        address: "23050 Via Villagio Pkwy, Estero, FL 33928",
        phone: "(239) 495-9296",
        website: "http://www.bonitasmokeshop.com",
        hours: "Monday-Saturday 9 AM-9 PM, Sunday 10 AM-6PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Bonita Beach, FL – Bonita Smoke Shop, a beloved local institution for over 30 years, is thrilled to announce its relocation and expansion to Coconut Point Shopping Center will be operating under Bonita Smoke Shop & Cigar Lounge.  The new location will feature a significantly expanded retail space boasting over 6,600 square feet dedicated to a world-class selection of cigars.",
        latitude: 26.40693,
        longitude: -81.809575,
        image: "/images/bonita/front.jpg",
        gallery: [
            "/images/bonita/front.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "24",
        slug: "tobacco-leaf",
        name: "Tobacco Leaf",
        city: "Jessup",
        stateabb: "MD",
        state: "Maryland",
        zip: "20794",
        address: "7395 Cedar Ave, Jessup, MD 20794",
        phone: "(239) 495-9296",
        website: "http://www.tobaccoleafmd.com",
        hours: "",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasEvents: true,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Tobacco Leaf is a multi-generational family owned brick and mortar shop that specializes in luxury tobacco and the finest smoking accessories. It’s humble beginnings can be traced back to 1982, when Harish Gupta opened a small 700 square foot store in Hunt Valley, MD.",
        latitude: 39.16826,
        longitude: -76.790209,
        image: "/images/tobaccoleaf/front.jpg",
        gallery: [
            "/images/tobaccoleaf/DSC_0756.jpg",
            "/images/tobaccoleaf/DSC_0837.jpg",
            "/images/tobaccoleaf/front.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "25",
        slug: "chesapeake-pipe-and-cigar",
        name: "Chesapeake Pipe & Cigar",
        city: "Annapolis",
        stateabb: "MD",
        state: "Maryland",
        zip: "21401",
        address: "45 Old Solomons Island Rd, Annapolis, MD 21401",
        phone: "(443) 949-9004",
        website: "http://www.chesapeakepipeandcigar.com",
        hours: "M-F 11 AM-8 PM, Sat & Sun 11 AM-7 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: false,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Get priority access to everything worth knowing about here at Chesapeake Pipe & Cigar though our NEW text-based information system.",
        latitude: 38.979253,
        longitude: -76.535463,
        image: "",
        gallery: [
            "",
                    ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.2,
        reviewCount: 102,
    },
    {
        id: "26",
        slug: "fifth-avenue-cgars",
        name: "5th Avenue Cigars",
        city: "Anchorage",
        stateabb: "AK",
        state: "Alaska",
        zip: "99501",
        address: "531 E 5th Ave, Anchorage, AK 99501",
        phone: "(907) 274-7473",
        website: "http://www.avenuecigars.com",
        hours: "M-Sat 10 AM-8 PM, Sun 3PM-9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "5th Avenue Cigars is Alaska's premier purveyor of fine tobacco products. We welcome you to Alaska's largest walk-in humidor, and largest cigar selection.",
        latitude: 61.217821,
        longitude: -149.874144,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "27",
        slug: "tobaccos-of-hawaii",
        name: "Tobaccos of Hawaii",
        city: "Honolulu",
        stateabb: "HI",
        state: "Hawaii",
        zip: "96826",
        address: "2043 S Beretania St, Honolulu, HI 96826",
        phone: "(808) 942-7855",
        website: "http://www.tobaccosofhawaii.com",
        hours: "M-Sat 9 AM-8 PM, Sun 9 AM- 6 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "At Tobaccos of Hawaii, we believe that Hawaii tobacco lovers deserve the very best quality and service from their smoke shop. We are tobacco enthusiasts just like you, and our staff is knowledgeable and courteous, friendly, and always professional.",
        latitude: 21.295983,
        longitude: -157.828801,
        image: "/images/tobaccosofhawaii/image1.jpg",
        gallery: [
            "/images/tobaccosofhawaii/image1.jpg",
            "/images/tobaccosofhawaii/image2.jpg",
            "/images/tobaccosofhawaii/image3.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "28",
        slug: "cigar-daddies",
        name: "Cigar Daddies",
        city: "Lacey",
        stateabb: "WA",
        state: "Washington",
        zip: "98503",
        address: "4511 Lacey Blvd SE, Lacey, WA 98503",
        phone: "(360) 491-5400",
        website: "https://www.thecigardaddies.com",
        hours: "M-F 11 AM-8 PM, Sat 11 AM- 6 PM, Sun 11 AM- 5 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "We Believe that wanting the best should never get in the way of wanting to relax..",
        latitude: 47.036296,
        longitude: -122.826037,
        image: "/images/cigardaddieswa/img1.jpg",
        gallery: [
            "/images/cigardaddieswa/img2.jpg",
            "/images/cigardaddieswa/img1.jpg",
                    ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "29",
        slug: "cigars-on-seventh",
        name: "Cigars on 7th",
        city: "Lacey",
        stateabb: "OR",
        state: "Oregon",
        zip: "97401",
        address: "679 Lincoln St, Eugene, OR 97401",
        phone: "(541) 654-5004",
        website: "https://cigarson7th.com",
        hours: "M-Sat 10 AM-7 PM, Sun 10 AM- 3 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "We Believe that wanting the best should never get in the way of wanting to relax..",
        latitude: 44.052408,
        longitude: -123.097094,
        image: "",
        gallery: [
            "",
            ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "30",
        slug: "churchill-cigar-lounge",
        name: "Churchill Cigar Lounge",
        city: "San Diego",
        stateabb: "CA",
        state: "California",
        zip: "92110",
        address: "2415 San Diego Ave, San Diego, CA 92110",
        phone: "(619) 546-7758",
        website: "https://churchillcigarlounge.com/",
        hours: "Sun-Thu 10 AM-10 PM, Fri & Sat 10 AM- Midnight",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 32.751718,
        longitude: -117.193959,
        image: "/images/churchill-sd/patio.jpeg",
        gallery: [
            "/images/churchill-sd/patio.jpeg",
            "/images/churchill-sd/cigarlist.png",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "31",
        slug: "big-smoke",
        name: "Big Smoke",
        city: "Boise",
        stateabb: "ID",
        state: "Idaho",
        zip: "83704",
        address: "6595 W Ustick Rd, Boise, ID 83704",
        phone: "(208) 376-9333",
        website: "http://www.bigsmokestores.com",
        hours: "Mon-Sat 7 AM-10 PM, Sun 8 AM- 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 43.633686,
        longitude: -116.263362,
        image: "/images/bigsmokeidaho/img1.jpg",
        gallery: [
            "/images/bigsmokeidaho/img1.jpg",
            "/images/bigsmokeidaho/big-smoke-logo.svg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "32",
        slug: "beehive-cigars",
        name: "Beehive Cigars",
        city: "Salt Lake City",
        stateabb: "UT",
        state: "Utah",
        zip: "84115",
        address: "1564 S 300 W, Salt Lake City, UT 84115",
        phone: "(801) 671-3612",
        website: "http://www.beehivecigars.com",
        hours: "Mon-Sat 10 AM-9 PM, Sun 11 AM- 7 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 43.633686,
        longitude: -116.263362,
        image: "/images/beehiveut/me2.avif",
        gallery: [
            "/images/beehiveut/me2.avif",
            "/images/beehiveut/tayler.avif",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    {
        id: "33",
        slug: "montecristo-cigar-bar",
        name: "Montecristo Cigar Bar",
        city: "Las Vegas",
        stateabb: "NV",
        state: "Nevada",
        zip: "89109",
        address: "3655 Las Vegas Blvd S, Las Vegas, NV 89109",
        phone: "(877) 796-2096",
        website: "https://www.caesars.com/paris-las-vegas/things-to-do/nightlife/montecristo-cigar-bar",
        hours: "Mon-Sun 11 AM - 1 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 36.112243, 
        longitude: -115.17042,
        image: "/images/montenv/image.jpg",
        gallery: [
            "/images/montenv/image.jpg",
            
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    {
        id: "34",
        slug: "castro-cigar-lounge",
        name: "Castro's Cigar Lounge",
        city: "Phoenix",
        stateabb: "AZ",
        state: "Arizona",
        zip: "85044",
        address: "4855 E Warner Rd, Phoenix, AZ, 85044",
        phone: "(480) 687-2850",
        website: "https://castroscigarbar.com/phoenix-cigar-bar/",
        hours: "Sun - Wed 10 AM- Midnight, Thu - Sat 10 AM - 2 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Our full craft bar in Phoenix (Ahwatukee) is designed for the discerning spirits enthusiast. From world-renowned whiskies + bourbons, to boutique and small batch releases - we've curated an amazing selection for you to enjoy.",
        latitude: 33.330843,
        longitude: -111.978521,
        image: "/images/castroaz/img1.jpg",
        gallery: [
            "/images/castroaz/img1.jpg",
            "/images/castroaz/img2.jpg",

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    {
        id: "35",
        slug: "padres-cigars",
        name: "Padres Cigars",
        city: "Corrales",
        stateabb: "NM",
        state: "New Mexico",
        zip: "87048",
        address: "4605 Corrales Rd. Corrales New Mexico 87048",
        phone: "",
        website: "https://www.padrescigars.com/home",
        hours: "Monday Closed, Tue, Wed, Thu, Sun 11 AM - 6 PM, Fri & Sat 11 AM - 8PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: false,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Our full craft bar in Phoenix (Ahwatukee) is designed for the discerning spirits enthusiast. From world-renowned whiskies + bourbons, to boutique and small batch releases - we've curated an amazing selection for you to enjoy.",
        latitude: 35.226303,
        longitude: -106.614444,
        image: "/images/padresnm/img1.jpg",
        gallery: [
            "/images/padresnm/img1.jpg",
            "/images/padresnm/img2.jpg",

        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    {
        id: "36",
        slug: "smoking-cave-cigar-lounge",
        name: "Smoking Cave Cigar Lounge",
        city: "Corrales",
        stateabb: "CO",
        state: "Colorado",
        zip: "80126",
        address: "5435 Boatworks Dr, Highlands Ranch, CO 80126",
        phone: "(303) 713-0022",
        website: "https://smokingcave.com/",
        hours: "Mon-Sat 8 AM - 10 PM, Sun 10 AM - 6 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: false,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Our full craft bar in Phoenix (Ahwatukee) is designed for the discerning spirits enthusiast. From world-renowned whiskies + bourbons, to boutique and small batch releases - we've curated an amazing selection for you to enjoy.",
        latitude: 39.565626,
        longitude: -104.924832,
        image: "/images/smokingcaveco/img1.jpg",
        gallery: [
            "/images/smokingcaveco/img1.jpg",
            "/images/smokingcaveco/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    {
        id: "37",
        slug: "habana-house-cigar-lounge-south-austin",
        name: "Habana House Cigar Lounge South Austin",
        city: "Austin",
        stateabb: "TX",
        state: "Texas",
        zip: "78704",
        address: "3601 S Congress Ave, Austin, TX 78704",
        phone: "(512) 447-9449",
        website: "http://www.habanahousecigarlounge.com",
        hours: "Mon-Thu 10 AM-830 PM, Fri & Sat 10 AM-10PM, Sun 10 AM-6 PM ",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Habana House Cigar Lounge is a well-established haven for cigar enthusiasts, proudly serving our community for 25 years. With two inviting lounges and a third on the horizon, we offer a sophisticated atmosphere for aficionados to relax, connect, and enjoy premium cigars. ",
        latitude: 30.227653,
        longitude: -97.760545,
        image: "/images/habanaTX/img1.jpg",
        gallery: [
            "/images/habanaTX/img1.jpg",
            "/images/habanaTX/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 132,
    },
    {
        id: "38",
        slug: "omerta-cigar-lounge",
        name: "Omerta Cigar Lounge",
        city: "Great Falls",
        stateabb: "MT",
        state: "Montana",
        zip: "59401",
        address: "3 4th Street North, Great Falls, Montana 59401",
        phone: "admin@omertacigarlounge.com",
        website: "https://omertacigarlounge.com/",
        hours: "Mon-Thu 10 AM-830 PM, Fri & Sat 10 AM-10PM, Sun 10 AM-6 PM ",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Welcome to Omerta Cigar Lounge Great Falls, MT",
        latitude: 47.505713,
        longitude: -111.300533,
        image: "/images/omertaMT/img1.jpg",
        gallery: [
            "/images/omertaMT/img1.jpg",
            "/images/omertaMT/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 32,
    },
    {
        id: "39",
        slug: "the-colonel-venue-and-cigar-lounge",
        name: "The Colonel Venue and Cigar Lounge",
        city: "Great Falls",
        stateabb: "WY",
        state: "Wyoming",
        zip: "82414",
        address: "1328 Beck Ave, Cody, WY 82414",
        phone: "(307) 578-8510",
        website: "https://www.thecolonelvenue.com",
        hours: "Thu 6 PM - 11 PM, Fri & Sat 6 PM - Midnight ",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "This warm environment features comfortable seating, stately furniture and a games table for those looking to enjoy a fun game of poker.",
        latitude: 47.505713,
        longitude: -111.300533,
        image: "/images/colWY/img1.jpg",
        gallery: [
            "/images/colWY/img1.jpg",
            "/images/colWY/img2.jpg"
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 32,
    },
    {
        id: "40",
        slug: "big-stick-cigar-lounge",
        name: "Big Stick Cigar Lounge",
        city: "Mandan",
        stateabb: "ND",
        state: "North Dakota",
        zip: "58554",
        address: "104 2nd Ave NW, Mandan, ND 58554",
        phone: "(701) 751-1029",
        website: "http://www.bigstickcigarsnd.com",
        hours: "Mon-Sat, Noon - 1 AM, Sun Noon-8 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Located in legendary downtown Mandan.  Big Stick Cigar Lounge is North Dakota's coolest vintage cigar lounge.",
        latitude: 46.826512,
        longitude: -100.892579,
        image: "/images/BigStickND/img1.avif",
        gallery: [
            "/images/BigStickND/img1.avif",
            "/images/BigStickND/img2.avif",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 4.8,
        reviewCount: 32,
    },
    {
        id: "41",
        slug: "the-sikar-cigar-lounge",
        name: "The Sikar Cigar Lounge",
        city: "Wilmington",
        stateabb: "DE",
        state: "Delaware",
        zip: "19806",
        address: "1624 Delaware Ave, Wilmington, DE 19806",
        phone: "(302) 655-2250",
        website: "https://www.facebook.com › SikarLounge",
        hours: "Sun - Thu 5 PM - Midnight, Fri & Sat 2 PM - 1 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Delaware's premiere cigar lounge located in the heart of Trolley Square!.",
        latitude: 39.757679, 
        longitude: -75.562577,
        image: "/images/sikarde/img1.jpg",
        gallery: [
            "/images/sikarde/img1.jpg",
            "/images/sikarde/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "42",
        slug: "tapp-that-ash-cigar-bar-and-lounge",
        name: "Tapp That Ash Cigar Bar & Lounge",
        city: "Franklington",
        stateabb: "NC",
        state: "North Carolina",
        zip: "27525",
        address: "22 S Main St, Franklinton, NC 27525",
        phone: "(919) 728-8106",
        website: "https://tappthatash.com",
        hours: "Wed-Sat 2 PM - 10 PM, Fri & Sat 2 PM - Midnight, Sun Noon - 8 PM, Mon & Tue 4 PM - 10 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Franklinton's premiere cigar & Bourbon Lounge.",
        latitude: 36.103023,
        longitude: -78.457354,
        image: "/images/tappthatnc/img1.jpg",
        gallery: [
            "/images/tappthatnc/img1.jpg",
            "/images/tappthatnc/img2.jpg", 
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "43",
        slug: "10-north-lounge",
        name: "10 North Lounge",
        city: "Atlantic City",
        stateabb: "NJ",
        state: "New Jersey",
        zip: "08401",
        address: "2831 Boardwalk, Atlantic City, NJ 08401",
        phone: "(800) 843-8767",
        website: "https://www.caesars.com › tropicana-ac › things-to-do › nightlife",
        hours: "24 hours!",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Sophisticated and upscale, sip top-shelf libations and stay close to the action with bar-top gaming, or get cozy around our statement double-sided fireplace.",
        latitude: 39.352361,
        longitude: -74.445377,
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "44",
        slug: "lite-um-up-cigars-lounge",
        name: "LITE UM UP CIGARS LOUNGE",
        city: "Columbia",
        stateabb: "SC",
        state: "South Carolina",
        zip: "29229",
        address: "4435 Hard Scrabble Rd, Columbia, SC 29229",
        phone: "(803) 708-4877",
        website: "http://liteumupcigars.net",
        hours: "Mon-Thu 11 AM- 8 PM, Fri & Sat 11 AM- 9 PM, Sun Noon - 7 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "WE ALWAYS HAVE A PLACE FOR YOU HERE AT LITE UM UP CIGARS",
        latitude: 34.146271,
        longitude: -80.911674,
        image: "/images/liteemsc/img1.jpg",
        gallery: [
            "/images/liteemsc/img1.jpg",
            "/images/liteemsc/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "45",
        slug: "casa-de-montecristo-cigar-lounge",
        name: "Casa de Montecristo Cigar Lounge",
        city: "Nashville",
        stateabb: "TN",
        state: "Tennessee",
        zip: "37203",
        address: "600 9th Ave S, Nashville, TN 37203",
        phone: "(615) 800-3397",
        website: "https://www.casademontecristo.com/nashville/?utm_source=partnerize&utm_medium=affiliate&utm_campaign=21181&utm_content=8-12854&clickId=5452823406",
        hours: "Mon-Thu 11 AM- 8 PM, Fri & Sat 11 AM- 9 PM, Sun Noon - 7 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "There’s always something happening at Casa de Montecristo, the premier destination for premium cigars and elevated cigar lounge experiences. From exclusive cigar tastings to signature events, this is your hub for everything happening at Casa.",
        latitude: 36.151613,
        longitude: -86.7799,
        image: "/images/casatn/img1.jpg",
        gallery: [
            "/images/casatn/img1.jpg",
            "/images/casatn/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "46",
        slug: "wild-bill-cigar-bar-and-lounge",
        name: "Wild Bill's Cigar Bar & Lounge",
        city: "Georgetown",
        stateabb: "KY",
        state: "Kentucky",
        zip: "40324",
        address: "401 Outlet Center, Drive Suite 340, Georgetown, KY 40324",
        phone: "(859) 575-7015",
        website: "https://leafandbarrellounge.com/",
        hours: "Mon - Thurs: 2 pm - 9 pm, Fri: 2 pm - 11 pm, Sat: 12 pm - 11 pm, Sun 1 PM - 6 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Whether you’re new to the cigar scene or you’ve been enjoying premium hand-rolled cigars for many years, Leaf & Barrel Cigar and Bourbon Lounge is excited for you to visit us in Georgetown or in our NEW location at 103 Big Hill Ave. in Richmond!",
        latitude: 38.217645,
        longitude: -84.537132,
        image: "/images/leafky/img1.jpg",
        gallery: [
            "/images/leafky/img1.jpg",
            "/images/leafky/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "47",
        slug: "cuban-creations-cigar-bar",
        name: "Cuban Creations Cigar Bar",
        city: "New Orleans",
        stateabb: "LA",
        state: "Louisiana",
        zip: "70130",
        address: "533 Toulouse St, New Orleans, LA 70130",
        phone: "(504) 372-4838",
        website: "http://www.cigarbarnola.com",
        hours: "Sun - Mon 11 AM - 2 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Welcome to Cuban Creations the best bar in New Orleans, where our delectable drinks and large variety of the finest premium and handmade sticks await you",
        latitude: 29.956509,
        longitude: -90.064252,
        image: "/images/cubanla/img1.jpeg",
        gallery: [
            "/images/cubanla/img1.jpeg",
            "/images/cubanla/img2.jpeg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "48",
        slug: "cigar-republic",
        name: "Cigar Republic",
        city: "Little Rock",
        stateabb: "AR",
        state: "Arkansas",
        zip: "72227",
        address: "1315 Breckenridge Dr, Little Rock, AR 72227",
        phone: "(501) 615-8040",
        website: "https://www.cigarrepublic.com/",
        hours: "Mon-Tue-Wed 1pm-11pm, Thur & Fri 1pm - Midnight, Sat 11am - Midnight, Sunday 3pm - 10pm",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Arkansas' Largest Walk-In Humidor",
        latitude: 34.766697,
        longitude: -92.386303,
        image: "/images/republicAR/img1.jpg",
        gallery: [
            "/images/republicAR/img1.jpg",
            "/images/republicAR/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
    {
        id: "49",
        slug: "safari-cigars-and-lounge",
        name: "Safari Cigars and Lounge",
        city: "Omaha",
        stateabb: "NE",
        state: "Nebraska",
        zip: "68164",
        address: "13110 Birch Dr, Omaha, NE 68164",
        phone: "(402) 965-1460",
        website: "  http://www.safaricigarsandlounge.com",
        hours: "Mon - Sat 9 AM - Midnight, Sun 11:45 AM - 10:30 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: true,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: false,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Creating the most unique and pleasurable cigar smoking experience in Omaha.",
        latitude: 41.291113,
        longitude: -96.119094,
        image: "/images/safarine/img1.jpg",
        gallery: [
            "/images/safarine/img1.jpg",
            "/images/safarine/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.2,
        reviewCount: 32,
    },
];