export type Shop = {
    id: string;
    slug: string;
    name: string;
    city: string;
    stateabb: string;
    state: string;
    zip: string;
    address: string;
    phone: string;
    website?: string;
    hours?: string;
    hasLounge: boolean;
    hasHumidor: boolean;
    hasPadrons: boolean;
    hasDavidoffs: boolean;
    hasOpusX: boolean;
    hasAcid: boolean;
    hasPipeTobacco: boolean;
    hasMemberAccess: boolean;
    hasliquorlicense: boolean;
    canbringinliquor: boolean;
    hasinternetaccess: boolean;
    hascoffeemaker: boolean;
    hasicemaker: boolean;
    hasBigTV: boolean;
    sellsAccessories: boolean;
    description: string;
    image?: string;
    gallery?: string[];
    isFeatured?: boolean;
    isSponsored?: boolean;
    rating?: number;
    reviewCount?: number;

};

export const shops: Shop[] = [
    {
        id: "1",
        slug: "davidus-cigars-annapolis",
        name: "Davidus Cigars- Annapolis",
        city: "Annapolis",
        stateabb: "MD",
        state: "Maryland",
        zip: "21401",
        address: "2134 Generals Hwy, Annapolis, MD 21401",
        phone: "(410) 573-1212",
        website: "http://www.davidus.com",
        hours: "M-TH 10 AM-9 PM, Fri and Sat 10AM-11PM, SUN 11 AM-7PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: true,
        hasicemaker: true,
        hasBigTV: true,
        sellsAccessories: false,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/front.jpg",
        gallery: [
            "/images/DavidusAnnapolis/cl-annapolis-3.jpg",
            "/images/DavidusAnnapolis/Davidus_Logo.png",
            "/images/DavidusAnnapolis/front.jpg",
            "/images/DavidusAnnapolis/cl-annapolis-11.jpg",
            "/images/DavidusAnnapolis/JohnS.jpg"
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 2.5,
        reviewCount: 131,
        },
    {
        id: "2",
        slug: "davidus-cigars-baltimore-federal-hill",
        name: "Davidus Cigars- Baltimore (Federal Hill)",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21230",
        address: "1011 Light St, Baltimore, MD 21230",
        phone: "(443) 449-5871",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/fedhill/baltimore_light_st._8.jpg",
        gallery: [
            "/images/fedhill/baltimore_light_st._8.jpg",
            "/images/fedhill/wedsite-managerBAL-LS.jpeg",
            "/images/fedhill/baltimore_light_st._6.jpg",
            "/images/fedhill/baltimore_light_st._7.jpg"
            
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
        },
    {
        id: "3",
        slug: "davidus-cigars-ellicott-city",
        name: "Davidus Cigars- Ellicott City",
        city: "Ellicott City",
        stateabb: "MD",
        state: "Maryland",
        zip: "21042",
        address: "9180 Baltimore National Pike, Ellicott City, MD 21042",
        phone: "(410) 480-4810",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/DavidusEllicott/Ellicottfront.jpg",
        gallery: [
            "/images/DavidusEllicott/Ellicott_Citymgr.jpg",
            "/images/DavidusEllicott/cl-ellicottcity-8.jpg",
            "/images/DavidusEllicott/Ellicottfront.jpg",
            "/images/DavidusEllicott/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 1.9,
        reviewCount: 15
        },
    {
        id: "4",
        slug: "davidus-cigars-ashton",
        name: "Davidus Cigars- Ashton",
        city: "Ashton",
        stateabb: "MD",
        state: "Maryland",
        zip: "20861",
        address: "25 Olney Sandy Spring Rd, Ashton, MD 20861",
        phone: "(301) 260-0788",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/Davidus-Ashton/ashtonmdlounge.jpg",
        gallery: [
            "/images/Davidus-Ashton/ashtonmdlounge.jpg",
            "/images/Davidus-Ashton/lounge2.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.4,
        reviewCount: 24,
        },
    {
        id: "5",
        slug: "broadleaf-tobacco",
        name: "Broadleaf Tobacco",
        city: "Severna Park",
        stateabb: "MD",
        state: "Maryland",
        zip: "21146",
        address: "487 Ritchie Hwy, Severna Park, MD 21146",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: "M-TH 10 AM-9 PM, Fri and Sat 10AM-11PM, SUN 11 AM-7PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: true,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Severna Park based Premium cigar shop with a comfortable lounge and curated humidor.",
        image: "/images/BLT/bltlounge1.jpg",
        gallery: [
            "/images/BLT/BLTlogo.png",
            "/images/BLT/BLTcrowd.jpg",
            "/images/BLT/bltlounge1.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 122,
    },
    {
        id: "6",
        slug: "aphelion-cigar-lounge",
        name: "Aphelion Cigar Lounge",
        city: "Gambrills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21054",
        address: "2510 Conway Rd, Gambrills, MD 21054",
        phone: "(410) 721-1700",
        website: "http://aphelioncigarlounge.com",
        hours: "Friday 10 AM - 2 AM, Saturday	10 AM - 1 AM, Sunday 10 AM - midnight, Easter, hours may vary, M-W 10 AM - midnight, Thursday 10AM-1 AM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasliquorlicense: true,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: true,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Aphelion is the FIRST Black Owned cigar lounge and full bar to open in the state of Maryland. The founder(s) and owners James Price and Robert Monroe are true pioneers with nearly 15 years in this amazing industry.",
        image: "",
        isFeatured: false,
        isSponsored: false,
        rating: 2.1,
        reviewCount: 44,
        },
    {
        id: "7",
        slug: "ashton-cigar-bar",
        name: "Ashton Cigar Bar",
        city: "Philadelphia",
        stateabb: "PA",
        state: "Pennsylvania",
        zip: "19102",
        address: "1522 Walnut St, Philadelphia, PA 19102",
        phone: "(410) 315-8118",
        website: "http://www.broadleaftobacco.net",
        hours: "M-TH 4 PM-11 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: false,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: false,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Modern, upscale cigar lounge and cocktail bar with an extensive menu of whiskey, cocktails, spirits, and cigars. Located above Holt’s Cigar Shop in downtown Philadelphia. You can still purchase cigars from the Holt's Cigar Shop online and in store.",
        image: "/images/ashtonpa/ashtonpa1.jpg",
        gallery: [
            "/images/ashtonpa/ashtonpa1.jpg",
            "/images/ashtonpa/logo.svg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.1,
        reviewCount: 1123,
        },
    {
        id: "8",
        slug: "casa-de-montecristo-cigar-lounge",
        name: "Casa de Montecristo Cigar Lounge",
        city: "New York City",
        stateabb: "NY",
        state: "New York",
        zip: "10022",
        address: "1016 2nd Ave, New York, NY 10022",
        phone: "(212) 750-0809",
        website: "",
        hours: "M-SUN 11AM-11 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasliquorlicense: false,
        canbringinliquor: false,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Casa De Montecristo New York – one of the finest cigar lounges in NYC. With its superb stogie collection, you’re guaranteed to find a cigar brand, type and size that meets your needs. Don’t worry if you’re a complete novice when it comes to cigars. Simply have a chat with a member of our onsite friendly and educated team.",
        image: "/images/casalogo.svg",
        gallery: [
            "/images/casademonte/casalogo.svg",
            
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "9",
        slug: "Windy-city-cigar-lounge",
        name: "Windy City Cigar Lounge",
        city: "Chicago",
        stateabb: "IL",
        state: "Illinois",
        zip: "60653",
        address: "4310 S Prairie Ave, Chicago, IL 60653",
        phone: "(773) 855-2143",
        website: "",
        hours: "Friday 5 PM - 1 AM, Saturday 5 PM - 1 AM, Sunday 11 AM - 11 PM, Easter, hours may vary, Monday & Tuesday Closed, Wednesday 5 PM - midnight, Thursday 5 PM - midnight",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "A cigar lounge for the sophisticated cigar aficionado",
        image: "",
        gallery: [
            "",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "10",
        slug: "magoo-cigar-lounge",
        name: "Magoo's Cigar Lounge",
        city: "Norfolk",
        stateabb: "VA",
        state: "Virginia",
        zip: "60653",
        address: "246 E Main St, Norfolk, VA 23510",
        phone: "(757) 937-5047",
        website: "",
        hours: "Friday & Saturday 11 AM - 10 PM, Sunday	Noon - 6 PM, Easter, hours may vary, M-TH 11 AM - 8:30 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Magoo's Cigar Lounge is a Cigar shop located in Norfolk.",
        image: "/images/magoos/magooslogo.jpg",
        gallery: [
            "/images/magoos/magooslogo.jpg",
            "/images/magoos/lounge1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "11",
        slug: "boston-cigar-lounge",
        name: "Boston Cigar Lounge",
        city: "Boston",
        stateabb: "MA",
        state: "Massachussetts",
        zip: "02129",
        address: "73 Main St, Boston, MA 02129",
        phone: "(617) 242-6010",
        website: "https://bostoncigarclub.com",
        hours: "Monday-Sunday 3 PM- 1 AM, Easter, hours may vary",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasliquorlicense: true,
        canbringinliquor: false,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Discover an unparalleled escape at Boston Cigar Club & Shop, a sophisticated destination where the worlds of premium cigars, exquisite spirits, and gourmet cuisine unite. Explore our extensive selection of fine tobacco in the dedicated cigar shop, boasting its own humidor. Then, unwind in our refined lounge, featuring a …",
        image: "/images/bostoncigar/bostonlounge1.jpg",
        gallery: [
            "/images/bostoncigar/bostonlounge1.jpg",
            "/images/bostoncigar/lounge2.jpg", 
        ],
        isFeatured: true,
        isSponsored: true,
        rating: 0.1,
        reviewCount: 1,
        },
    {
        id: "12",
        slug: "prime-cigar-bar",
        name: "Prime Cigar",
        city: "Atlanta",
        stateabb: "GA",
        state: "Georgia",
        zip: "30309",
        address: "1035 Peachtree St NE, Atlanta, GA 30309",
        phone: "(404) 941-7130",
        website: "https://primecigaratl.com/",
        hours: "Monday-Sunday 3 PM- 1 AM, Easter, hours may vary",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasliquorlicense: true,
        canbringinliquor: false,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "Welcome to Atlanta’s Most Premier Cigar Lounge. Let’s dine, drink, smoke.  Enjoy from a selection of our handcrafted cocktails or one of your favorite premium drinks. Our bartender will be sure to have you coming back all night long.",
        image: "/images/atlantaprime/InteriorShot-scaled.jpg",
        gallery: [
            "/images/atlantaprime/InteriorShot-scaled.jpg",
                    ],
        isSponsored: true,
        rating: 3.1,
        reviewCount: 54,
    },
    {
        id: "13",
        slug: "titan-cigar",
        name: "Titan Cigar",
        city: "Gambrills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21054",
        address: "2634 Chapel Lake Dr, Gambrills, MD 21054",
        phone: "410-721-0100",
        website: "https://titancigar.com/",
        hours: "Monday-Sunday 3 PM- 1 AM, Easter, hours may vary",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasliquorlicense: true,
        canbringinliquor: false,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: false,
        description: "Visit us in The Village at Waugh Chapel, Gambrills, Maryland. We offer a wide variety of premium and hard-to-find cigars, as well as accessories like humidors, lighters, and cutters. Our friendly and knowledgeable staff are here to assist you with your selections.",
        image: "/images/titan/titanfront.jpg",
        gallery: [
            "/images/titan/titanfront.jpg"
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 2.1,
        reviewCount: 94,
    },
    {
        id: "14",
        slug: "davidus-cigars-towson",
        name: "Davidus Cigars- Towson",
        city: "Towson",
        stateabb: "MD",
        state: "Maryland",
        zip: "21204",
        address: "25 Allegheny Ave, Towson, MD 21204",
        phone: "(410) 616-9906",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/towson/cl-towson-1.jpg",
        gallery: [
            "/images/towson/cl-towson-1.jpg",
            "/images/towson/towsonmgr.jpg",
            "/images/towson/cl-towson-10.jpg",
            "/images/towson/cl-towson-4.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "15",
        slug: "davidus-cigars-westminster",
        name: "Davidus Cigars- Westminster",
        city: "Westminster",
        stateabb: "MD",
        state: "Maryland",
        zip: "21157",
        address: "23 East Main Street, Westminster, MD 21157",
        phone: "(410) 876-4786",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/westminster/cl-westminster-1.jpg",
        gallery: [
            "/images/westminster/wedsite-managerWES.jpg",
            "/images/westminster/cl-westminster-8.jpg",
            "/images/westminster/cl-westminster-4.jpeg",
            "/images/westminster/cl-westminster-1.jpg"
            
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "16",
        slug: "davidus-cigars-frederick",
        name: "Davidus Cigars- Frederick",
        city: "Frederick",
        stateabb: "MD",
        state: "Maryland",
        zip: "21071",
        address: "​529 West South Street, Frederick, MD 21157",
        phone: "301-662-6606",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/frederick/cl-frederick-7.jpg",
        gallery: [
            "/images/frederick/Frederick-manager.jpg",
            "/images/frederick/cl-frederick-3.jpg",
            "/images/frederick/cl-frederick-1.jpg",
            "/images/frederick/cl-frederick-7.jpg",
                   ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "17",
        slug: "davidus-cigars-urbana",
        name: "Davidus Cigars- Urbana",
        city: "Urbana",
        stateabb: "MD",
        state: "Maryland",
        zip: "21704",
        address: "8925 Fingerboard Road, Urbana, MD 21704",
        phone: "301-874-1100",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/cl-urbanasouthfrederick-1.jpg",
        gallery: [
            "/images/urbana/cl-urbanasouthfrederick-6.jpg",
            "/images/urbana/wedsite-managerURB.jpg",
            "/images/urbana/cl-urbanasouthfrederick-9.jpg",
            "/images/urbana/cl-urbanasouthfrederick-1.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "18",
        slug: "davidus-cigars-shady-grove",
        name: "Davidus Cigars- Shady Grove",
        city: "Shady Grove",
        stateabb: "MD",
        state: "Maryland",
        zip: "20877",
        address: "15922 Shady Grove Road, Gaithersburg, MD 20877",
        phone: "301-963-8400",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: true,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/shady/cl-shadygroveroad-14.jpg",
        gallery: [
            "/images/shady/cl-shadygroveroad-manager-bc-jen.jpg",
            "/images/shady/cl-shadygroveroad-4.jpg",
            "/images/shady/cl-shadygroveroad-14.jpg",
            "/images/shady/cl-shadygroveroad-7.jpg",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.2,
        reviewCount: 80,
    },
    {
        id: "19",
        slug: "davidus-cigars-owings-mills",
        name: "Davidus Cigars- Owings Mills",
        city: "Owings Mills",
        stateabb: "MD",
        state: "Maryland",
        zip: "21117",
        address: "10810 Reisterstown Road, Owings Mills, MD 21117",
        phone: "443-449-5871",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/owings/cl-owingsmills-2.jpg",
        gallery: [
            "/images/owings/Owings_Mills-_Reisterstown.jpg",
            "/images/owings/img-2614_orig.jpg",
            "/images/owings/front",
            "/images/owings/cl-owingsmills-2.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.7,
        reviewCount: 70,
    },
    {
        id: "20",
        slug: "davidus-cigars-baltimore-little-italy",
        name: "Davidus Cigars- Baltimore (Little Italy)",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "21231",
        address: "1300 Bank Street (Central Ave), Baltimore, MD 21231",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/Daviduslittleitaly/image_10.jpg",
        gallery: [
            "/images/Daviduslittleitaly/image_6.jpg.jpg",
            "/images/Daviduslittleitaly/wedsite-manageritaly.jpeg",
            "/images/Daviduslittleitaly/image_10.jpg",
            "/images/Daviduslittleitaly/image_13.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "21",
        slug: "davidus-cigars-rockville",
        name: "Davidus Cigars- Rockville",
        city: "Baltimore",
        stateabb: "MD",
        state: "Maryland",
        zip: "20852",
        address: "11632 Rockville Pike, Rockville, MD 20852",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/image_6.jpg",
        gallery: [
            "/images/rocvkille/wedsite-managerROC_copy.jpg",
            "/images/rockville/cl-rockvillepike-1.jpg",
            "/images/rockville/cl-rockvillepike-4.jpg",
            "/images/rockville/cl-rockvillepike-7.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
    {
        id: "22",
        slug: "davidus-cigars-eldersburg",
        name: "Davidus Cigars- Eldersburg",
        city: "Eldersburg",
        stateabb: "MD",
        state: "Maryland",
        zip: "21784",
        address: "11716 Liberty Road, Eldersburg, MD 21784",
        phone: "410-276-3800",
        website: "http://davidus.com",
        hours: "Friday & Saturday 10 AM -11 PM, Sunday 11 PM - 7 AM, M-Thu 10 AM - 9 PM",
        hasLounge: false,
        hasHumidor: true,
        hasPadrons: true,
        hasDavidoffs: false,
        hasOpusX: true,
        hasAcid: true,
        hasPipeTobacco: true,
        hasMemberAccess: false,
        hasliquorlicense: false,
        canbringinliquor: true,
        hasinternetaccess: true,
        hascoffeemaker: false,
        hasicemaker: false,
        hasBigTV: true,
        sellsAccessories: true,
        description: "The world's best cigars in twelve Maryland locations. Visit Davidus Cigars today and relax in our LORD BALTIMORE CIGAR lounges. Home of Castro Brothers cigars and pipe tobaccos.",
        image: "/images/eldersburg/cl-eldersburg-7.jpg",
        gallery: [
            "/images/eldersburg/cl-eldersburg-7.jpg",
            "/images/eldersburg/eldersburg-manager.jpg",
            "/images/eldersburg/front.jpg",
            "/images/eldersburg/cl-eldersburg-5.jpg"
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 4.2,
        reviewCount: 100,
    },
];