import type { Shop } from "./types";

export const southdakotaShops: Shop[] = [
    {
        id: "1",
        slug: "deadwood-tobacco-co-and-cigar-bar",
        name: "Deadwood Tobacco Co. and Cigar Bar",
        city: "Deadwood",
        stateabb: "SD",
        state: "South Dakota",
        zip: "57732",
        address: "715 Main St, Deadwood, SD 57732",
        phone: "(605) 722-1510",
        website: "http://www.deadwoodtobacco.com",
        hours: {
            mon: "10AM- 6PM",
            tue: "10AM- 6PM",
            wed: "10AM- 6PM",
            thu: "10AM- 10PM",
            fri: "10 AM- Midnight",
            sat: "10 AM- Midnight",
            sun: "10AM- 6PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "The new Deadwood Tobacco is at 715 Main Street featuring the largest humidor in the state, a 6,000 sq. ft. lounge and venue, an immerse bar with the best local and regional taps.",
        latitude: 44.375491,
        longitude: -103.731411,
        image: "/images/deadwoodSD/img1.jpg",
        gallery: [
            "/images/deadwoodSD/img1.jpg",
            "/images/deadwoodSD/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]