export type Shop = {
    id: string;
    slug: string;
    name: string;
    city: string;
    state: string;
    stateabb: string;
    zip: string;
    address: string;
    phone: string;
    website?: string;
    hours?: {
        mon?: string;
        tue?: string;
        wed?: string;
        thu?: string;
        fri?: string;
        sat?: string;
        sun?: string;
    };
    description: string;
    image?: string;
    latitude?: number;
    longitude?: number;

    hasLounge?: boolean;
    hasHumidor?: boolean;
    sellsAccessories?: boolean;

    hasDavidoffs?: boolean;
    hasPadrons?: boolean;
    hasFuentes?: boolean;
    hasOpusX?: boolean;
    hasRareOpusX?: boolean;
    hasAcid?: boolean;
    hasPerdomos?: boolean;
    hasLFDs?: boolean;
    hasOlivas?: boolean;
    hasAtabeys?: boolean;
    hasHouseCigars?: boolean;
    hasAltadis?: boolean;
    hasGeneralCigar?: boolean;

    hasMemberLockers?: boolean;
    sellsFood?: boolean;
    hasPipeTobacco?: boolean;
    hasMemberAccess?: boolean;
    hasEvents?: boolean;
    hasHooka?: boolean;
    hasLiquorLicense?: boolean;
    canBringInLiquor?: boolean;
    hasInternetAccess?: boolean;
    hasCoffeeMaker?: boolean;
    hasIceMaker?: boolean;
    hasBigTV?: boolean;
    gallery?: string[];
    rating?: number;
    reviewCount?: number;
    isFeatured?: boolean;
    isSponsored?: boolean;
};