import type { Shop } from "./types";

export const utahShops: Shop[] = [
    {
        id: "1",
        slug: "beehive-cigars",
        name: "Beehive Cigars",
        city: "Salt Lake City",
        stateabb: "UT",
        state: "Utah",
        zip: "84115",
        address: "1564 S 300 W, Salt Lake City, UT 84115",
        phone: "(801) 671-3612",
        website: "http://www.beehivecigars.com",
        hours: {
            mon: "10AM - 9PM",
            tue: "10AM - 9PM",
            wed: "10AM - 9PM",
            thu: "10AM - 9PM",
            fri: "10AM - 9PM",
            sat: "10AM - 9PM",
            sun: "11AM - 7PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: true,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "An outdoor patio of tables and chairs with a big screen tv, 20 taps for beer, shelves of great wine, a merchandise store with apparel and accessories and of course walls of cigars of every type.",
        latitude: 43.633686,
        longitude: -116.263362,
        image: "/images/beehiveut/me2.avif",
        gallery: [
            "/images/beehiveut/me2.avif",
            "/images/beehiveut/tayler.avif",
        ],
        isFeatured: false,
        isSponsored: false,
        rating: 3.0,
        reviewCount: 12,
    },
    ]