import type { Shop } from "./types";

export const washingtonShops: Shop[] = [
    {
        id: "1",
        slug: "cigar-daddies",
        name: "Cigar Daddies",
        city: "Lacey",
        stateabb: "WA",
        state: "Washington",
        zip: "98503",
        address: "4511 Lacey Blvd SE, Lacey, WA 98503",
        phone: "(360) 491-5400",
        website: "https://www.thecigardaddies.com",
        hours: {
            mon: "11AM - 8PM",
            tue: "11AM - 8PM",
            wed: "11AM - 8PM",
            thu: "11AM - 8PM",
            fri: "11AM - 8PM",
            sat: "11AM - 6PM",
            sun: "11AM - 5PM"
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: true,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "We Believe that wanting the best should never get in the way of wanting to relax..",
        latitude: 47.036296,
        longitude: -122.826037,
        image: "/images/cigardaddieswa/img1.jpg",
        gallery: [
            "/images/cigardaddieswa/img2.jpg",
            "/images/cigardaddieswa/img1.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]