import type { Shop } from "./types";

export const wisconsinShops: Shop[] = [
    {
        id: "1",
        slug: "appleton-cigar-co",
        name: "Appleton Cigar Co.",
        city: "Appleton",
        stateabb: "WI",
        state: "Wisconsin",
        zip: "54911",
        address: "415 W College Ave, Appleton, WI 54911",
        phone: "(920) 830-8349",
        website: "http://www.appletoncigar.com",
        hours: {
            mon: "11:30 AM-10:30 PM",
            tue: "11:30 AM-10:30 PM",
            wed: "11:30 AM-10:30 PM",
            thu: "11:30 AM-10:30 PM",
            fri: "11:30 AM-10:30 PM",
            sat: "11:30 AM-10:30 PM",
            sun: "11:30 AM-10:30 PM",
        },
        hasLounge: true,
        hasHumidor: true,
        hasPadrons: false,
        hasFuentes: true,
        hasDavidoffs: false,
        hasOpusX: false,
        hasAcid: true,
        hasPerdomos: true,
        hasLFDs: true,
        hasOlivas: true,
        hasAtabeys: false,
        hasHouseCigars: true,
        hasAltadis: true,
        hasGeneralCigar: true,
        hasRareOpusX: false,
        hasMemberLockers: true,
        sellsFood: false,
        hasPipeTobacco: false,
        hasMemberAccess: false,
        hasEvents: false,
        hasHooka: true,
        hasLiquorLicense: false,
        canBringInLiquor: true,
        hasInternetAccess: true,
        hasCoffeeMaker: false,
        hasIceMaker: false,
        hasBigTV: false,
        sellsAccessories: true,
        description: "Appleton Souvenir & Cigar Co. (ASCC) opened on April 1st, 1997, as a souvenir, apparel, and small selection of premium cigar store under the ownership of Mary Weidert.",
        latitude: 44.261542,
        longitude: -88.411363,
        image: "/images/public/appletonWI/img1.jpg",
        gallery: [
            "/images/public/appletonWI/img1.jpg",
            "/images/public/appletonWI/img2.jpg",
        ],
        isFeatured: false,
        isSponsored: true,
        rating: 3.0,
        reviewCount: 12,
    },
    ]